### ISSUE TITLE
[Step2] Vanilla Javascript로 무작정 TodoList 만들기(전진우)

### ISSUE THREAD

**Issue by Jun-Jinu** [DKU-D-Coding/js-study-make-framework-lv1#10]
<h2>노션으로 작성해서 링크도 함께 첨부합니다! </h2>

https://discreet-snowshoe-17f.notion.site/Step-2-Vanilla-Javascript-TodoList-bcc7fdfd62d94516bef0d18dba1b862c

<h3>이론</h3>
<ul>
<li>
<p>[x]  Javascript Array Method에 대해 조사하고 간단한 예제 코드 추가하기</p>
<ul>
<li>[x]  Array.prototype.map()</li>
</ul>
<pre><code class="language-jsx">// 콜백 함수를 이용해서 배열 또는 객체 각각의 요소를 호출해서 그 값을 변환함

let arr = [1, 2, 3, 4];

//인자는 순서대로 현재 요소, 인덱스, 전체 array 객체를 전달합니다.
// 80 자리에는 this의 값을 변경합니다. 기본값: undefined
let tempArr = arr.map((element, index, array) =&gt; {
	return element * 3;
}, 80);

console.log(tempArr); // [3, 6, 9, 12]
</code></pre>
<ul>
<li>[x]  Array.prototype.filter()</li>
</ul>
<pre><code class="language-jsx">// 배열에 조건을 적용해서 반환하는 매서드
let arr = [1, 2, 3, 4];

let tempArr = arr.filter(element =&gt; element &lt; 3 );

console.log(tempArr); // [1, 2]
</code></pre>
<ul>
<li>[x]  Array.prototype.reduce()</li>
</ul>
<pre><code class="language-jsx">// 배열의 각 요소에 주어진 리듀서 함수를 실행, 하나의 결과값 반환하는 매서드
let arr = [1, 2, 3, 4];

let value = 0;
let sumAllValue = arr.reduce(
	(total, currentValue) =&gt; total + currentValue,
	value
);

console.log(sumAtValue); // 10

//array.reduce(function(total, currentValue, currentIndex, arr), initialValue)
//가 모든 인자이며 순서대로,, 이전까지의 결과값, 이번에 적용할 값, 
// 이번에 적용할 인덱스, 모든 배열, 최초 적용할 값이다.
</code></pre>
<ul>
<li>[x]  Array.prototype.forEach()</li>
</ul>
<pre><code class="language-jsx">// 각각 배열 요소에 함수를 실행하는 매서드
let arr = [1, 2, 3, 4];

arr.forEach(element =&gt; console.log(element));

//1
//2
//3
//4
</code></pre>
<ul>
<li>[x]  Array.prototype.some()</li>
</ul>
<pre><code class="language-jsx">// 배열에 어떤 요소라도 통과하는지 테스트(있으면 true, 없으면 false)
let arr = [1, 2, 3, 4];

let odd = (element) =&gt; element % 2 === 1;

console.log(arr.some(odd));
// true
</code></pre>
<ul>
<li>[x]  Array.prototype.every()</li>
</ul>
<pre><code class="language-jsx">// 배열에 모든 요소가 통과하는지 테스트(있으면 true, 없으면 false)
let arr = [1, 2, 3, 4];

let odd = (element) =&gt; element % 2 === 1;
let singleDigint = (element) =&gt; element &lt; 10;

console.log(arr.some(odd));
// false

console.log(arr.some(singleDigint));
// true
</code></pre>
<ul>
<li>[x]  Array.prototype.find()</li>
</ul>
<pre><code class="language-jsx">// 배열에 판별 함수를 만족하는 첫 요소의 값 반환(있으면 값, 없으면 undefined)
const arr = [1, 2, 3, 4];

const even = arr.find(element =&gt; element % 2 === 0);

console.log(even);
// 2
</code></pre>
<ul>
<li>[x]  Array.prototype.findIndex()</li>
</ul>
<pre><code class="language-jsx">// 배열에 판별 함수를 만족하는 첫 요소의 값 반환(있으면 인덱스, 없으면 -1)
const arr = [1, 2, 3, 4];

const even = arr.findIndex(element =&gt; element % 2 === 0);

console.log(even);
// 1
</code></pre>
<ul>
<li>[x]  Array.prototype.includes()</li>
</ul>
<pre><code class="language-jsx">// 배열에 특정 요소를 포함하고 있는지 판별
const arr = [1, 2, 3, 4];

console.log(arr.includes(3));
// true

console.log(arr.includes(9));
// false
</code></pre>
<ul>
<li>[x]  Array.prototype.push()</li>
</ul>
<pre><code class="language-jsx">// 배열에 새로운 요소를 추가합니다
const arr = [1, 2, 3, 4];

arr.push(5);

console.log(arr); // [1, 2, 3, 4, 5]
</code></pre>
<ul>
<li>[x]  Array.prototype.splice()</li>
</ul>
<pre><code class="language-jsx">// 기존 요소에 원하는 자리에 제거, 변경, 추가합니다
// splice(start, deleteCount, item1, item2, itemN)
const elements = ['D', 'Coding', 'Frontend'];

console.log(elements.splice(2, 1, 'React', 'Study'));
// ['D', 'Coding', 'React', 'Study']
</code></pre>
<ul>
<li>[x]  Array.prototype.slice()</li>
</ul>
<pre><code class="language-jsx">// slice(start, end)
// start부터 end 전까지의 배열 객체를 반환합니다
// 음수이면 끝에서 n번째를 의미합니다
const elements = ['D', 'Coding', 'Frontend'];

console.log(elements.slice(0, 2));
// ['D', 'Coding']

console.log(elements.slice(0, -1));
// ['D', 'Coding']
</code></pre>
<ul>
<li>[x]  Array.prototype.shift()</li>
</ul>
<pre><code class="language-jsx">// 배열에 첫 요소를 떼어냅니다. 따라서 배열 길이도 변합니다
const arr = [1, 2, 3, 4];

const firstElement = arr.shift();

console.log(arr);
// [2, 3, 4];

console.log(firstElement);
// 1
</code></pre>
<ul>
<li>[x]  Array.prototype.unshift()</li>
</ul>
<pre><code class="language-jsx">// unshift(element0, element1, elementN)
// 배열에 앞 요소를 만듭니다. 배열 길이가 늘어납니다.
// 늘어난 배열 길이를 반환합니다.
const arr = [1, 2, 3, 4];

console.log(arr.unshift(-1, 0));
// 6

console.log(arr);
// [-1, 0, 1, 2, 3, 4];
</code></pre>
<ul>
<li>[x]  Array.prototype.concat()</li>
</ul>
<pre><code class="language-jsx">// concat(value0, value1, valueN)
// 배열들을 병합합니다. 기존 배열은 변하지않고 반환값으로 만들어집니다.
const arr1 = [1, 2, 3, 4];
const arr2 = [5, 6, 7, 8];
const arr3 = arr1.concat(arr2);

console.log(arr3);
// [1, 2, 3, 4, 5, 6, 7, 8]
</code></pre>
<ul>
<li>[x]  Array.prototype.join()</li>
</ul>
<pre><code class="language-jsx">// 모든 요소를 지정된 문자열로 구분해서 합친 문자열로 반환합니다.
// 기본값: ,
const elements = ['D', 'Coding', 'Frontend'];

console.log(elements.join());
//D,Coding,Frontend

console.log(elements.join(''));
//DCodingFrontend

console.log(elements.join('-'));
// D-Coding-Frontend
</code></pre>
<ul>
<li>[x]  Array.prototype.reverse()</li>
</ul>
<pre><code class="language-jsx">// 배열 요소가 반대로 뒤집힙니다
const elements = ['D', 'Coding', 'Frontend'];

console.log(elements.reverse());
// ['Coding', 'Frontend', 'D']
</code></pre>
<ul>
<li>[x]  Array.prototype.sort()</li>
</ul>
<pre><code class="language-jsx">// 배열 요소를 정렬합니다
const elements = ['D', 'Coding', 'Frontend'];

console.log(elements.sort());
// ['Coding', 'D', 'Frontend']
</code></pre>
<ul>
<li>[x]  Array.prototype.flat()</li>
</ul>
<pre><code class="language-jsx">// flat(depth)
// 지정된 깊이까지 연결된 새 배열을 만듭니다.
// 깊이란 연산 재귀 횟수를 의미합니다
// 기본값은 1

const arr = [1, 2, [[3, 4]]];

console.log(arr.flat());
// [1, 2, [3, 4]]

console.log(arr.flat(2));
// [1, 2, 3, 4]
</code></pre>
<ul>
<li>[x]  Array.prototype.flatMap()</li>
</ul>
<pre><code class="language-jsx">// arr.map(...args).flat()과 기능은 같으나 더 효율적(flat의 깊이는 1인 상태)
// flatMap((element, index, array) =&gt; { })
// 인자 및 돌아가는 방식은 map과 같음

const arr = [1, 2, [3, 4]];

console.log(arr.flatMap(num =&gt; num * 3));
// [3, 6, 9, 12]
</code></pre>
<ul>
<li>[x]  Array.prototype.fill()</li>
</ul>
<pre><code class="language-jsx">// fill(value, start, end)
// value 값을 start부터 end 전까지 채웁니다
// 배열의 길이는 변하지 않습니다

const arr = [1, 2, 3, 4];

console.log(arr.fill(0));
// [0, 0, 0, 0]

console.log(arr.fill(0, 2));
// [1, 2, 0, 0]

console.log(arr.fill(0, 2, 3));
// [1, 2, 0, 4]

</code></pre>
<ul>
<li>[x]  Array.prototype.pop()</li>
</ul>
<pre><code class="language-jsx">// 배열에 마지막 요소를 빼고 반환합니다
const arr = [1, 2, 3, 4];

console.log(arr.pop()); // 4

console.log(arr); // [1, 2, 3]
</code></pre>
<ul>
<li>[x]  Array.prototype.indexOf()</li>
</ul>
<pre><code class="language-jsx">// 배열에서 지정된 요소를 찾을 수 있는 첫 번째 인덱스 반환
// 없으면 -1 반환
const arr = ['1', '2', '3', '4' ,'1'];

console.log(arr.indexOf('1')); // 1

console.log(arr.indexOf('1', 2)); // 4 (index 2부터 시작)

console.log(arr.indexOf('5')); // -1
</code></pre>
<ul>
<li>[x]  Array.prototype.from()</li>
</ul>
<pre><code class="language-jsx">// Array.from(arrayLike, (element, index) =&gt; { })
// arrayLike로 새로운 배열로 각 요소로 만들고
// 뒤의 함수는 각 요소에 대해 연산합니다

console.log(Array.from('Dcoding'));
// ['D', 'C', 'o', 'd', 'i', 'n', 'g']

console.log(Array.from([1, 2, 3, 4], num =&gt; num * 3));
// [3, 6, 9, 12]
</code></pre>
</li>
<li>
<p>[x]  ECMAScript와 Javascript의 차이점에 대해 조사하기 (5문장 요약)</p>
</li>
<li>
<p>자바스크립트가 ECMAScript 사용을 준수하는 객체 기반의 스크립트 프로그래밍 언어임. 즉 하위 개념입니다.</p>
</li>
<li>
<p>ECMAScript는 스크립트 언어가 준수해야 하는 규칙, 세부 사항 및 지침을 제공합니다.</p>
</li>
<li>
<p>따라서 ECMAScript가 업데이트되면 기능 적용을 위해 Javascript 엔진도 업데이트가 필요합니다.</p>
</li>
<li>
<p>그래서 호환성 관점에서 Javascript 엔진이 ECMAScript를 얼마나 잘 적용하는지가 중요한 부분입니다.</p>
</li>
<li>
<p>따라서 개발자가 사용하는 건 실질적으로 Javascript입니다.</p>
</li>
<li>
<p>[x]  Javascript의 프로토타입에 대해 조사하기 (5문장 요약)</p>
</li>
<li>
<p>자바스크립트에서는 객체를 상속하기 위하여 프로토타입이라는 방식을 사용합니다.</p>
</li>
<li>
<p>자바스크립트에서는 현재 존재하고 있는 객체를 프로토타입으로 사용하여, 해당 객체를 복제하여 재사용하는 것을 상속이라고 합니다.</p>
</li>
<li>
<p>자바스크립트의 모든 객체는 최소한 하나 이상의 다른 객체로부터 상속을 받으며, 이때 상속되는 정보를 제공하는 객체를 프로토타입(prototype)이라고 합니다.</p>
</li>
<li>
<p>프로토타입 객체도 또 다시 상위 프로토타입 객체로부터 메소드와 속성을 상속 받을 수도 있고 그 상위 프로토타입 객체도 마찬가지입니다. 이를 프로토타입 체인(prototype chain)이라고 합니다.</p>
</li>
<li>
<p>자바스크립트에서는 객체 인스턴스와 프로토타입 간에 연결(많은 브라우저들이 생성자의 <code>prototype</code> 속성에서 파생된 <code>__proto__</code> 속성으로 객체 인스턴스에 구현하고 있습니다.)이 구성되며 이 연결을 따라 프로토타입 체인을 타고 올라가며 속성과 메소드를 탐색합니다.</p>
</li>
<li>
<p>[x]  Javascript의 클로저에 대해 조사하기 (5문장 요약)</p>
</li>
<li>
<p>자신을 포함하고 있는 외부함수보다 내부함수가 더 오래 유지되는 경우, 외부 함수 밖에서 내부함수가 호출되더라도 외부함수의 지역 변수에 접근할 수 있는데 이러한 함수를 말합니다.</p>
</li>
<li>
<p>아래 조사한 실행 컨텍스트 관점에서는 내부함수가 유효한 상태에서 외부함수가 종료하여 외부함수의 실행 컨텍스트가 반환되어도 외부함수 실행 컨텍스트 내의 활성객체는 내부함수에 의해 참조되는 한 유효하여 내부함수가 스코프 체인을 통해 참조할 수 있는것입니다!</p>
</li>
<li>
<p>즉 외부함수가 이미 반환되었어도 외부함수 내의 변수는 이를 필요로 하는 내부함수가 하나 이상 존재하면 계속 유지됩니다.</p>
</li>
<li>
<p>이 내부함수는 외부함수에 있는 변수의 복사본이 아니라 실제 변수에 접근하는것 입니다.</p>
</li>
<li>
<p>따라서 클로저는 자신이 생성될 때의 렉시컬 환경(Lexical environment)을 기억하므로 메모리 차원에서는 손해 볼 수 있지만 비공개 변수를 만들어 활용하므로 정보 은닉으로 인한 사용자 통제, 컨텍스트의 소멸되지 않음으로 인한 상태 기억등 다양한 이점을 얻을 수 있습니다.</p>
</li>
<li>
<p>[x]  Javascript의 스코프에 대해 조사하기 (5문장 요약)</p>
</li>
<li>
<p>참조 대상 식별자를 찾아내기 위한 규칙이다. 즉, 변수 및 함수에 접근하기 위한 유효범위이다.</p>
</li>
<li>
<p>사용되는 변수는 var, const, let이 있으며 차이는 아래 표와 같다.</p>

변수 | 재할당 | 재선언 | 범위
-- | -- | -- | --
var | 가능 | 불가능 | 블록 및 함수 스코프
const | 불가능 | 불가능 | 블록 및 함수 스코프
let | 가능 | 불가능 | 함수 스코프

</li>
<li>
<p>var은 블록 스코프를 무시하고 블록 밖에서도 쓰일 수 있다.</p>
</li>
<li>
<p>블록 스코프는 function 을 제외한 if나 for 등의 '{ }' 안에 있는 범위를 의미한다.</p>
</li>
<li>
<p>또한 함수 스코프는 fuction의 { }를 의미한다.</p>
</li>
<li>
<p>[x]  Javascript의 this에 대해 조사하기 (5문장 요약)</p>
</li>
<li>
<p>자바스크립트의 예약어이다.</p>
</li>
<li>
<p>전역에서 선언된 함수의 경우 window 객체를 반환한다.</p>
</li>
<li>
<p>this는 자신이 속한 객체 또는 자신이 생성할 인스턴스를 가리키는 자기 참조 변수(self-reference variable)이다.</p>
</li>
<li>
<p>따라서 this를 통해 자신이 속한 객체 또는 자신이 생성할 인스턴스의 프로퍼티나 메서드를 참조할 수 있다.</p>
</li>
<li>
<p>화살표 함수의 경우 항상 상위 스코프의 this를 가지는데 이를 <code>렉시컬 this</code> 라 한다. 따라서 this에 바인딩할 객체가 정적으로 결정되고 apply, bind, call 메서드로 this 변경이 불가능하다.</p>
</li>
<li>
<p>반면에 일반 함수는 선언시 this에 바인딩할 객체가 정적으로 결정되지 않고, 함수를 호출 할 때 함수가 어떻게 호출 되는지에 따라 this에 바인딩할 객체가 동적으로 결정된다.</p>
</li>
<li>
<p>[x]  Javascript의 실행컨텍스트에 대해 조사하기 (10문장 요약)</p>
</li>
<li>
<p>자바스크립트 코드가 실행되고 연산되는 범위를 나타내는 추상적인 개념입니다.</p>
</li>
<li>
<p>실행할 코드에 제공할 환경 정보들을 모아놓은 객체입니다</p>
</li>
<li>
<p>전역 컨텍스트가 만들어지고 함수 호출 시마다 컨텍스트가 생깁니다.</p>
</li>
<li>
<p>컨텍스트 생성 시 컨텍스트 안에는 변수 객체, scope chain, this가 생성됩니다.</p>
</li>
<li>
<p>함수가 실행되면 사용되는 변수들은 변수 객체 안에서 값을 찾고 없다면 스코프 체인을 따라가며 찾습니다.</p>
</li>
<li>
<p>함수 실행이 마무리되면 해당 컨텍스트는 사라집니다. 따라서 페이지가 종료되면 전역 컨텍스트도 사라집니다.</p>
</li>
<li>
<p>상위 컨텍스트의 Lexcical Environment 정보를 참조하는데 이를 통해 스코프 및 스코프 체인의 개념이 생깁니다.</p>
</li>
<li>
<p>Lexcical Environment는 함수 실행 도중에 변경 사항이 즉시 반영되고 컨텍스트가 존재하는 한 계속 저장됩니다. 이는 클로저를 존재할 수 있게합니다.</p>
</li>
<li>
<p>호이스팅이란</p>
<ul>
<li>변수를 선언, 초기화했을 때 선언 부분이 최상단으로 끌어올려지는 현상(변수는 선언 부분, 함수는 함수 전체가 됨)입니다.</li>
<li>하지만 변수에 함수를 할당할 경우 호이스팅되지 않습니다.</li>
</ul>
</li>
<li>
<p>[x]  Javascript의 이벤트에 대해 조사하기 (5문장 요약)</p>
<ul>
<li>[x]  이벤트 위임</li>
<li>하위 요소에 각각 이벤트를 붙이지 않고 상위 요소에서 하위 요소의 이벤트를 제어하는 방식입니다.</li>
<li>즉, 자신에게 발생한 이벤트를 다른 요소에서 처리하는 것입니다.</li>
<li>컨테이너에 하나의 핸들러 할당 → 핸들러의 event.target을 사용해 이벤트가 발생한 요소가 어디인지 알아냄 → 원하는 요소의 이벤트 발생이 확인되면 이벤트 핸들링</li>
<li>장점으로는 많은 핸들러를 할당하지 않아도 되기 때문에 초기화가 단순하고 메모리가 절약됩니다.</li>
<li><code>document.onclick</code>은 중복으로 인한 충돌을 일으킬 가능성이 있으므로   <code>addEventListener</code> 을 사용하는 것을 권장한다고 합니다.</li>
<li>[x]  이벤트 버블링</li>
<li>특정 화면 요소에서 이벤트 발생시 이벤트가 더 상위의 화면 요소들로 전달되어가는 특성을 의미합니다.</li>
<li>event.stopPropagation() 메서드를 통해서 버블링을 인위적으로 막을 수 있습니다.</li>
<li>[x]  이벤트 캡처링</li>
<li>버블링과 반대로 진행되는 전파 방식입니다.</li>
<li>즉, 이벤트가 발생한 지점을 찾아내려가는 것을 의미합니다.</li>
</ul>
</li>
</ul>
<hr>
<h3>실습 - JS로 TodoList 만들기</h3>
<ul>
<li>[x]  목록</li>
<li>[x]  추가</li>
<li>[x]  수정</li>
<li>[x]  삭제</li>
<li>[x]  토글</li>
</ul>

**Comment by JunilHwang** [comment]
> Javascript의 프로토타입에 대해 조사하기 (5문장 요약)

그렇다면 왜 하필 프로토타입을 도입하게 되었을까요!?

> 따라서 클로저는 자신이 생성될 때의 렉시컬 환경(Lexical environment)을 기억하므로 메모리 차원에서는 손해 볼 수 있지만 비공개 변수를 만들어 활용하므로 정보 은닉으로 인한 사용자 통제, 컨텍스트의 소멸되지 않음으로 인한 상태 기억등 다양한 이점을 얻을 수 있습니다.

클로저를 소멸시킬 수 있는 방법은 아예 없을까요?

> 사용되는 변수는 var, const, let이 있으며 차이는 아래 표와 같다.

var와 let이 서로 바뀐 것 같아요! 그리고 const와 let은 "함수 및 블록"이 아니라 "블록" 이라고 보시면 좋을 것 같아요! 결국 함수에서 블록을 사용하니까요 ㅋㅋ

> 이벤트 버블링과 캡처링 

버블링과 캡처링 중에 어떤게 먼저 실행될까요!?

> 기타 질문

```js
const Foo = function () {
  this.method2 = function () {
    console.log('this is method2 of Foo');
  }
}

Foo.prototype.method1 = function() {
  console.log('this is method1 of Foo');
}

const foo = new Foo();
foo.method1();
foo.method2();
```

여기서 method1과 method2는 메모리에 대한 관점에서 어떤 차이가 있을까요?

**Comment by ho991217** [comment]
> 여기서 method1과 method2는 메모리에 대한 관점에서 어떤 차이가 있을까요?

메서드1은 Foo의 프로토타입에 바로 바인딩 되어있어서 Foo의 모든 인스턴스들이 공유하기 떄문에 인스턴스를 몇 개를 만들어도 메모리에 딱 한번 저장되지만,
메서드 2는 Foo의 생성자의 this에 직접 연결되어 있어서 인스턴스가 만들어 질 때마다 함수의 복사본이 만들어져서 매번 새로운 메모리 공간을 잡아먹읍니다.
<sub> 지나가다가 입이 근질근질해서... </sub>

**Comment by JunilHwang** [comment]
@ho991217 @Jun-Jinu 
```js
class Foo {
  method1 = () => console.log('this is method1 of Foo');
  method2 () { console.log('this is method2 of Foo') }
}

const foo = new Foo();
foo.method1();
foo.method2();
```
이건 어떨까요!?

**Comment by ho991217** [comment]
> 이건 어떨까요!?

일반 함수로 선언 된 메서드 `method2`는 `this`가 동적으로 바인딩 되기 떄문에 호출 할 떄마다 메모리에 할당되지만 화살표 함수인 `method1`은 `this`가 항상 상위 스코프의 `this`로 정적 바인딩 되기 때문에 상대적으로 화살표 함수로 선언 된 `method1`메모리 측면에서 효율적이지 않을가요
그리고 일반 함수와 달리 화살표 함수는 호이스팅이 일어나지 않기 떄문에 실행 전에 쓰이는 메모리 공간을 조금 더 효율적으로 관리할 수 있을거구요
...라고 생각합니당

**Comment by JunilHwang** [comment]
@ho991217 ㅋㅋㅋㅋ 정확히 반대로 답변하셨답니다

**Comment by ho991217** [comment]
헉ㅠㅠ

**Comment by JunilHwang** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/18749057/216056492-d4cd7043-a14a-420f-88bc-610f5614336a.png">

**Comment by JunilHwang** [comment]
여기서 this 바인딩(화살표함수)과는 별개로

method1은 "인스턴스"에 할당되고 (왜냐하면 멤버변수에 할당했기 때문에!)
method2는 "프로토타입"에 할당됩니다.

그래서 
```js
class Foo {
  method1 = function () {
    console.log('this is method1 of Foo');
  }
}
```

이렇게 선언하는 경우에도 멤버변수에 할당하는거라서, 인스턴스가 만들어질 때 마다 함수도 같이 정의된답니다!

**Comment by ho991217** [comment]
> 여기서 this 바인딩(화살표함수)과는 별개로
> 
> 
> 
> method1은 "인스턴스"에 할당되고 (왜냐하면 멤버변수에 할당했기 때문에!)
> 
> method2는 "프로토타입"에 할당됩니다.
> 
> 
> 
> 그래서 
> 
> ```js
> 
> class Foo {
> 
>   method1 = function () {
> 
>     console.log('this is method1 of Foo');
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> 이렇게 선언하는 경우에도 멤버변수에 할당하는거라서, 인스턴스가 만들어질 때 마다 함수도 같이 정의된답니다!

함수 선언식과 함수 표현식의 차이었네요!
