### ISSUE TITLE
[Step2] Vanilla Javascript로 무작정 TodoList 만들기 (김채은)

### ISSUE THREAD

**Issue by chchaeun** [DKU-D-Coding/js-study-make-framework-lv1#11]
### Array.prototype.map()
배열 요소들에 대해 인자로 주어진 함수를 호출한 결과를 모아 새로운 배열을 반환한다.

```javascript
const arr = [1, 2, 3, 4];

const mapArr = arr.map((value, index, array) => value + index); // [1, 3, 5, 7]
// value: 현재 요소, index: 현재 요소의 인덱스, array: 호출한 배열
```

### Array.prototype.filter()
배열에서 인자로 주어진 함수의 조건이 참이 되는 요소들을 모아 새로운 배열로 반환한다.

```javascript
const arr = [1, 2, 3, 4];

const filterArr = arr.filter((value, index, array) => value > 2); // [3, 4]
```

### Array.prototype.reduce()
배열의 각 요소에 대해 이전 상태와 동작을 받아 새 상태를 리턴한다.
```javascript
const arr = [1, 2, 3, 4];

const initialValue = 0;
const reduceValue = arr.reduce((accumulator, currentValue, index, array) => accumulator + currentValue, initialValue);
// accumulator: 누적 값, currentValue: 현재 요소
// initialValue: 초기값, 없으면 배열의 첫 번째 인자

// reduceValue: 10 (0+1+2+3+4)
```

### Array.prototype.forEach()
주어진 함수를 배열 요소 각각에 대해 실행한다. 리턴이 없다.

```javascript
const arr = [1, 2, 3, 4];
arr.forEach((value, index, array) => console.log(value));
// 1
// 2
// 3
// 4
```

### Array.prototype.some()
배열 안의 요소 중 적어도 하나라도 주어진 함수에 대해 참인지 반환한다.
```javascript
const arr = [1, 2, 3, 4];

const result = arr.some(value => value < 0); // false
```

### Array.prototype.every()
배열 안의 모든 요소가 주어진 함수에 대해 참인지 반환한다.
```javascript
const arr = [1, 2, 3, 4];

const result = arr.some(value => value > 0); // true
```

### Array.prototype.find()
배열 요소 중 주어진 함수를 만족하는 첫 번째 요소의 값을 반환한다. 그런 요소가 없다면 `undefined`를 반환한다.
```javascript
const arr = [1, 2, 3, 4];

const result = arr.find(value => value > 2); // 3
```
### Array.prototype.findIndex()
배열 요소 중 주어진 함수를 만족하는 첫 번째 요소의 인덱스를 반환한다. 그런 요소가 없다면 `-1`을 반환한다.
```javascript
const arr = [1, 2, 3, 4];

const result = arr.find(value => value > 2); // 2
```
### Array.prototype.includes()
배열이 특정 요소를 포함하고 있는지 판별한다.

```javascript
const arr = [1, 2, 3, 4];

const result = arr.includes(2); // true
```

### Array.prototype.push()
배열의 끝에 하나 이상의 요소를 추가하고, 배열의 새로운 길이를 반환한다.

```javascript
const arr = [1, 2];

const count = arr.push(3);
// count: 3
// arr: [1, 2, 3]

arr.push(4, 5);
// arr: [1, 2, 3, 4, 5]
```
### Array.prototype.splice()
배열 기존 요소를 삭제, 교체하거나 새 요소를 추가한다.

```javascript
const arr = [0, 2, 3, 4];

// array.splice(start[, deleteCount[, item1[, item2[, ...]]]])
// start: 배열 변경을 시작할 인덱스, deleteCount: 제거할 요소의 수, item: 추가할 요소

arr.splice(1, 0, 1); // [0, 1, 2, 3, 4]
arr.splice(0, 2) // [2, 3, 4]
arr.splice(2, 1, 5) // [2, 3, 5]
```

### Array.prototype.slice()
배열에서 주어진 인덱스 범위에 대한 얕은 복사를 새로운 배열로 반환한다. 원본 배열은 바뀌지 않는다.
```javascript
const arr = [1, 2, 3, 4];
const sliceArr1 = arr.slice(1); // [2, 3, 4]
const sliceArr2 = arr.slice(2, 3) // [3]
const sliceArr3 = arr.slice(-2); // [3, 4]
```
### Array.prototype.shift()
배열 첫 번째 요소를 제거하고 제거된 요소를 반환한다.
```javascript
const arr = [1, 2, 3];
const shiftReturn = arr.shift();
// shiftReturn: 1, arr: [2, 3]
```

### Array.prototype.unshift()
배열 맨 앞에 새로운 요소를 추가하고 새로운 길이를 반환한다.
```javascript
const arr = [1, 2, 3];
const unshiftReturn = arr.unshift(0, 1, 2);
// unshiftReturn: 6, arr: [0, 1, 2, 1, 2, 3]
```

### Array.prototype.concat()
배열 혹은 값을 기존 배열에 합쳐 새 배열을 반환한다. 원본 배열을 변경하지 않는다.
```javascript
const arr1 = [1, 2];
const arr2 = [3, 4];
const value = 5;

const result1 = arr1.concat(arr2); // [1, 2, 3, 4]
const result2 = arr1.concat(arr2, value) // [1, 2, 3, 4, 5] 
```

### Array.prototype.join()
배열 요소를 연결해 하나의 문자열으로 반환한다. 원본 배역을 변경하지 않는다.
```javascript
const arr = ['a', 'b', 'c'];
const joinArr1 = arr.join() // a,b,c
const joinArr2 = arr.join("?") // a?b?c
```

### Array.prototype.reverse()
배열의 순서를 반전한다. 원본 배열을 변환한다.
```javascript
const arr = [1, 2, 3]
arr.reverse();
// arr: [3, 2, 1]
```

### Array.prototype.sort()
배열의 요소를 정렬한다. 인자가 없을 땐 유니코드 코드 포인트에 따라, 인자로 함수가 주어질 땐 정의된 정렬 순서에 따라 정렬한다. 원본 배열을 변경한다.
```javascript
const arr1 = [3, 1, 2];
arr.sort() // [1, 2, 3]

const arr2 = ['b', 'c', 'a'];
arr2.sort() // ['a', 'b', 'c'];

const arr3 = [1, 5, 3];
arr3.sort((a, b) => b - a); // [5, 3, 1]
// compareFunction(a, b)가 0보다 작은 경우 a가 먼저, 0이면 변경 안함, 0보다 큰 경우 b가 먼저 온다.
```
### Array.prototype.flat()
배열의 하위 배열 요소를 지정한 깊이까지 재귀적으로 이어붙인 새로운 배열이다. 원본 배열을 변경한다.
```javascript
const arr1 = [1, 2, [3, 4]];
arr1.flat(); // [1, 2, 3, 4]

const arr2 = [1, 2, [3, [4, 5]]];
arr2.flat(2); // [1, 2, 3, 4, 5]

const arr3 = [1, 2, [3, [4, 5]]];
arr2.flat(); // [1, 2, 3, [4, 5]]
```
### Array.prototype.flatMap()
매핑함수로 각 요소에 대해 함수를 수행하고 결과에 대해 flat 함수를 수행한다. 원본 배열을 변경하지 않는다.
단어 리스트를 생성할 때 유용하다.
```javascript
const arr = ['hello world', '', 'javascript'];
arr.flatMap(value => value.split(" ");
// ['hello', 'world', 'javascript']
```
### Array.prototype.fill()
배열의 시작 인덱스부터 끝 인덱스 이전까지 정적인 값으로 채운다. 배열을 초기화할 때 유용하다.
```javascript
const arr = [1, 2, 3, 4];
arr.fill(0, 1, 3); // [1, 0, 0, 4]
arr.fill(1, 2) // [1, 0, 1, 1]

Array(5).fill(0); // [0, 0, 0, 0, 0]
```
### Array.prototype.pop()
배열 마지막 요소를 제거하고 제거된 요소를 반환한다.
```javascript
const arr = [1, 2, 3, 4];
const result = arr.pop();
// result: 4, arr: [1, 2, 3]
```

### Array.prototype.indexOf()
배열 중에서 인자로 받은 요소를 찾아 첫 번째 요소의 인덱스를 반환한다. 존재하지 않으면 `-1`을 반환한다.
```javascript
const arr = [1, 2, 3, 4, 3];
const result1 = arr.indexOf(3); // 2

// 두 번째 인자는 탐색을 시작할 인덱스 번호이다.
const result2 = arr.indexOf(3, 3) // 4
```

### Array.prototype.from()
유사 배열 객체 또는 반복 가능한 객체를 얕게 복사해 새로운 배열 객체를 만든다.
```javascript
Array.from('abc'); // ['a', 'b', 'c']

// 첫 번째 매개변수: 유사 배열 객체나 반복 가능한 객체
// 두 번째 매개변수: 매핑 함수
Array.from({length: 3}, (v, i) => i); // [0, 1, 2]
```

## Javascript의 프로토타입에 대해 조사하기 (5문장 요약)
자바스크립트는 프로토타입 기반 언어인데, 어떤 객체를 원형으로 삼고 이블 복제(참조)함으로써 상속과 비슷한 효과를 얻는 것이다. 자바스크립트는 함수에 자동으로 객체인 `prototype` 프로퍼티를 생성해놓는데, `new` 연산자와 함께 함수를 호출할 경우(함수를 생성자 함수로서 사용할 경우), 그로부터 생성된 인스턴스에는 숨겨진 프로퍼티인 `__proto__`가 자동으로 생성되며, 이 프로퍼티는 생성자 함수의 `prototype` 프로퍼티를 참조한다. `__proto__` 프로퍼티는 생략 가능하므로 생성자 함수의 `prototype`에 어떤 메서드나 프로퍼티가 있다면 인스턴스에서도 마치 자신의 것처럼 해당 메서드나 프로퍼티에 접근할 수 있다.

## Javascript의 클로저에 대해 조사하기 (5문장 요약)
중첩함수가 상위 스코프의 식별자를 참조하고 외부함수보다 더 오래 유지되는 경우 이를 클로저라고 한다. 외부 함수의 `LexicalEnvironment`가 가비지 컬렉팅되지 않는 현상이다. 클로저는 콜백 함수 내부에서 외부 데이터를 사용하고자 할 때나, 접근 권한을 제어하여 정보를 은닉하고 싶을 때, 부분 적용 함수, 커링 함수 등에 사용할 수 있다.

## Javascript의 스코프에 대해 조사하기 (5문장 요약)
스코프는 변수에 접근할 수 있는 범위이다. 전역 스코프는 전역에 선언돼있어 어디서든 접근 가능하고, 지역 스코프는 지역에 선언돼있어 해당 지역에서만 접근 가능하다(Ex. 함수 스코프). 현재 자신의 스코프에서 사용하고자 하는 변수가 없을 때 상위 스코프에서 찾아 변수를 사용하는 것을 스코프 체인이라고 한다. 예를 들어 함수 내부에서 어떤 변수를 사용하는데 그 변수가 함수 스코프에 없을 경우 전역 스코프에서 찾아서 사용할 수 있다.

## Javascript의 this에 대해 조사하기 (5문장 요약)
대부분 객체지향 언어에서 this는 클래스로 생성한 인스턴스 객체를 의미하지만, 자바스크립트에서의 this는 어디서든 사용할 수 있고, 상황에 따라 바라보는 대상이 달라진다. this는 함수를 호출할 때 결정된다. 기본적으로 전역 공간에서의 this는 전역 객체(window)이고, 함수가 메서드로서 호출될 때(객체에 관한 동작을 수행할 때)는 앞에 명시된 객체가 this가 된다. 자바스크립트의 메서드를 사용하여 명시적으로 this를 바인딩할 수 있다. ex) call, apply, bind

## Javascript의 실행컨텍스트에 대해 조사하기 (10문장 요약)
실행 컨텍스트란 실행할 코드에 제공할 환경 정보들을 모아 놓은 객체이다. 실행 컨텍스트는 논리적 스택 구조를 가지며, 실행되는 순서대로 콜 스택에 쌓였다가 가장 위에 쌓여있는 컨텍스트와 관련있는 코드를 실행하는 방식으로 동일한 환경과 순서를 보장한다. 실행 컨텍스트 객체에 담기는 정보는 다음과 같다.
- `VariableEnvironment`: 현재 컨텍스트 내 식별자들에 대한 정보. LexicalEnvironment의 스냅샷으로, 변경 사항이 반영되지 않음.
- `LexicalEnvironment`: 자바스크립트 코드에서 변수나 함수 등의 식별자를 정의하는 데 사용하는 객체. 처음엔 VariableEnvironment와 같지만, 변경 사항이 실시간으로 반영됨.
- `ThisBinding`: 식별자가 바라보는 대상 객체
코드를 실행할 땐 `LexicalEnvironment`에 있는 정보들을 이용하게 된다. `LexicalEnvironment`의 내부는 다음과 같이 구성된다.
- `environmentRecord`: 현재 컨텍스트와 관련된 코드의 식별자 정보들이 저장된다. 이로 인해 호이스팅이 발생한다.
- `outerEnvironmentReference`: 상위 컨텍스트의 LexicalEnvironment를 참조한다. 이로 인해 스코프 체인이 형성된다.

## Javascript의 이벤트에 대해 조사하기 (5문장 요약)
브라우저가 처리해야 할 특정 사건이 발생했을 때 이를 감지하여 이벤트를 발생시킨다. 이벤트가 발생했을 때 이벤트 핸들러가 호출되고, 이를 통해서 사용자와 애플리케이션이 상호작용한다. 이처럼 프로그램의 흐름을 이벤트 중심으로 제어하는 방식을 이벤트 드리븐 프로그래밍이라 한다.

### 이벤트 캡처링
DOM 요소에서 발생하는 이벤트 객체는 이벤트 타깃을 중심으로 DOM 트리를 통해 전파된다. 이 과정 중 이벤트가 상위 요소에서 하위 요소 방향으로 전파되는 것을 이벤트 캡처링이라고 한다. 이벤트 핸들러 등록 방식 중 어트리뷰트/프로퍼티 방식에서는 캡처링 단계의 이벤트를 캡처할 수 없지만 addEventListener 방식에서는 3번째 인수를 통해 선별적으로 캐치할 수 있다.

### 이벤트 버블링
한 요소에 이벤트가 발생하면 이 요소에 할당된 핸들러가 동작하고, 이어서 부모 요소의 핸들러가 동작한다. 가장 최상단의 조상 요소를 만날 때까지 이 과정이 반복되며 요소 각각에 할당된 핸들러가 동작하는데, 이러한 흐름을 이벤트 버블링이라고 한다. 이벤트 버블링을 중단하기 위해서 `event.stopPropagation()` 메서드를 사용할 수 있다.

### 이벤트 위임
여러 개의 하위 요소들에 각각 이벤트 핸들러를 등록하지 않고 하나의 상위 요소에 핸들러를 등록하는 방법이다. 하위 요소에서 발생한 이벤트가 상위 요소로 흐르는 이벤트 버블링을 이용하여 이벤트 핸들러를 쉽게 관리하고, 동적인 엘리먼트에 대한 이벤트 처리를 수월하게 하는 방법으로 사용할 수 있다.

**Comment by JunilHwang** [comment]
1. Javascript는 도대체 왜 Prototype이라는 개념을 사용한걸까요? 
2. React에서는 이 클로저가 어디서 이용되고 있을까요?
3. js에서 method와 function의 차이가 뭘까요?
```js
var num = 100;
function fn() {
  console.log(this.num);
}
const foo = { num: 1000 };
const bar = { num: 2000 };
foo.fn = fn;
bar.fn = foo.fn;

foo.fn(); // 1
bar.fn(); // 2
fn(); // 3

foo.fn === bar.fn; // 4
fn === foo.fn; // 5
fn === bar.fn; // 6
```
1 ~ 6에는 각각 어떤 값이 출력될까요?

4. 이벤트 버블링은, 어째서 버블링이라는 이름을 갖게 된걸까요?
5. 버블링 vs 캡처링 -> 어떤게 먼저 실행될까요?

**Comment by chchaeun** [comment]
1. 메모리를 적게 사용하기 때문에 가볍다. 확장성이 높다.
2. React에서 함수 컴포넌트를 사용할 때 렌더링이 발생하면 함수 자체가 다시 호출된다. 그래서 상태를 관리하려면 함수가 다시 호출됐을 때 이전 상태를 기억하고 있어야 한다. 따라서 useState를 사용하여, 컴포넌트 외부에 값을 저장하고 클로저를 통해 값에 접근해 상태를 비교 변경한다. 
3. 메서드는 객체의 프로퍼티로 정의된 함수이다. 함수는 독립적으로 호출할 수 있으나 메서드는 인스턴스를 통해 호출해야 한다.
	- 1. 1000
	- 2. 1000 -> 2000 // 암시적 바인딩. Fn 함수를 호출한 객체에 this가 바인딩 됨.
	- 3. 100
	- 4. true
	- 5. false -> true // 비교연산자가 함수를 비교할 때 어떻게 동작하는지 모르겠습니다
	- 6. false -> true
4. 버블정렬의 버블과 비슷한 의미일 거라 생각한다. 원소의 이동이 거품이 수면으로 올라오는듯한 모습을 보이기 때문에. 
```
It happens when an element receives an event, and that event bubbles up (or you can say is transmitted or propagated) to its parent and ancestor elements in the DOM tree until it gets to the root element.
```
5. W3C 모델에서 이벤트가 발생하면 이벤트 캡처링이 먼저 일어나고 이벤트 타겟 도착 후 버블링이 일어난다.
