### ISSUE TITLE
[Step2] Vanilla Javascript로 무작정 TodoList 만들기 (이호연) 

### ISSUE THREAD

**Issue by ho991217** [DKU-D-Coding/js-study-make-framework-lv1#14]
### 이론

- [ ]  Javascript Array Method에 대해 조사하고 간단한 예제 코드 추가하기
    - [ ]  Array.prototype.map()
        
        설명 : 
        
        설명 : `Array.prototype.map()` 메소드는 배열 내 모든 요소에 대해 각각 주어진 함수를 호출한 결과를 모아 새로운 배열을 반환합니다. 이 메소드는 배열의 각 요소를 변형하는데 사용됩니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const calAtt = arr.map(x =>  x * 2)
        ```
        
    - [ ]  Array.prototype.filter()
        
        설명 :
        
        설명 : `Array.prototype.filter()` 메소드는 배열에서 특정 조건을 만족하는 모든 요소를 모아 새로운 배열로 반환합니다. 이 메소드는 배열의 각 요소에 대하여 제공된 함수를 테스트하고 그 결과가 참인 요소만 새로운 배열로 모아 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const even = arr.filter(x => x % 2 === 0)
        ```
        
    - [ ]  Array.prototype.reduce()
        
        설명 : `Array.prototype.reduce()` 메소드는 배열 내의 숫자 요소들을 하나의 값으로 줄이는데 사용합니다. 배열 내의 숫자 요소를 누적하여 연산하는데 유용합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.reduce((accumulator, currentValue) => accumulator + currentValue, 0);
        ```
        
    - [ ]  Array.prototype.forEach()
        
        설명 : `Array.prototype.forEach()` 메소드는 배열의 각 요소를 순회하며, 주어진 함수를 실행합니다. 이 함수는 실행될 때마다 요소값, 인덱스, 배열 자체를 인자로 전달받습니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        arr.forEach((value, index, array) => {
          console.log(value, index, array);
        });
        ```
        
    - [ ]  Array.prototype.some()
        
        설명 : `Array.prototype.some()` 메소드는 배열 내 어느 하나라도 주어진 판별 함수를 통과하는지 테스트합니다. 결과가 true라면, 검사는 즉시 중단됩니다. 배열 내의 모든 요소가 판별 함수를 통과하지 못하면, 결과는 false가 됩니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.some(x => x % 2 === 0)
        ```
        
    - [ ]  Array.prototype.every()
        
        설명 : `Array.prototype.every()` 메소드는 배열 내 모든 요소가 주어진 판별 함수를 통과하는지 테스트합니다. 결과가 false라면, 검사는 즉시 중단됩니다. 배열 내의 모든 요소가 판별 함수를 통과하면, 결과는 true가 됩니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.every(x => x % 2 === 0)
        ```
        
    
    - [ ]  Array.prototype.find()
        
        설명 : `Array.prototype.find()` 메소드는 배열 내에서 값을 찾아 해당 요소를 반환합니다. 만약 찾으려는 값이 없다면, `undefined`를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.find(x => x > 3)
        ```
        
    - [ ]  Array.prototype.findIndex()
        
        설명 : `Array.prototype.findIndex()` 메소드는 배열 내에서 값을 찾은 후 해당 요소의 인덱스를 반환합니다. 만약 찾으려는 값이 없다면, `-1`을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.findIndex(x => x > 3)
        ```
        
    
    - [ ]  Array.prototype.includes()
        
        설명 : `Array.prototype.includes()` 메소드는 배열 내 특정 요소가 존재하는지 확인합니다. 찾고자 하는 값이 있으면 true를 반환하고, 그렇지 않으면 false를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.includes(3)
        ```
        
    - [ ]  Array.prototype.push()
        
        설명 : `Array.prototype.push()` 메소드는 배열의 끝에 새 요소를 추가합니다. 이 메소드는 새로운 길이를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.push(6)
        ```
        
    - [ ]  Array.prototype.splice()
        
        설명: `Array.prototype.splice()` 메소드는 배열의 요소를 추가, 제거, 교체합니다. 이 메소드는 수정된 배열의 새로운 길이를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.splice(2, 0, 6)
        ```
        
    - [ ]  Array.prototype.slice()
        
        설명: `Array.prototype.slice()` 메소드는 배열의 부분 배열을 반환합니다. 이 메소드는 새로운 배열을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.slice(1, 4)
        ```
        
    - [ ]  Array.prototype.shift()
        
        설명 : `Array.prototype.shift()` 메소드는 배열의 첫 번째 요소를 제거하고 반환합니다. 배열의 길이는 하나 줄어듭니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.shift()
        ```
        
    - [ ]  Array.prototype.unshift()
        
        설명 : `Array.prototype.unshift()` 메소드는 배열의 시작 위치에 새 요소를 추가합니다. 이 메소드는 새로운 길이를 반환합니다. 인자로는 
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.unshift(0)
        ```
        
    - [ ]  Array.prototype.concat()
        
        설명 : `Array.prototype.concat()` 메소드는 다른 배열과 값을 결합하여 새 배열을 생성합니다. 이 메소드는 새로운 배열을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr1 = [1, 2, 3, 4, 5];
        const arr2 = [6, 7, 8];
        const result = arr1.concat(arr2)
        ```
        
    - [ ]  Array.prototype.join()
        
        설명 : `Array.prototype.join()` 메소드는 배열의 모든 요소를 하나의 문자열로 결합합니다. 이 메소드는 결합된 문자열을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.join('-')
        ```
        
    - [ ]  Array.prototype.reverse()
        
        설명: `Array.prototype.reverse()` 메소드는 배열의 순서를 반대로 뒤집습니다. 이 메소드는 배열 자체를 반대로 뒤집고 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.reverse()
        ```
        
    - [ ]  Array.prototype.sort()
        
        설명: `Array.prototype.sort()` 메소드는 배열 요소를 정렬합니다. 이 메소드는 배열 자체를 정렬하고 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 5, 3, 4, 2];
        const result = arr.sort()
        ```
        
    - [ ]  Array.prototype.flat()
        
        설명: `Array.prototype.flat()` 메소드는 배열의 모든 중첩 배열을 일렬로 펼쳐줍니다. 이 메소드는 새로운 배열을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, [2, 3], [4, 5]];
        const result = arr.flat()
        ```
        
    - [ ]  Array.prototype.flatMap()
        
        설명: `Array.prototype.flatMap()` 메소드는 배열의 각 요소를 매핑하고 그 결과를 깊이 1로 합칩니다. 반환되는 값은 배열이며, 함수의 각 결과가 합쳐진 것 입니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.flatMap(x => [x, x + 1])
        ```
        
    - [ ]  Array.prototype.fill()
        
        설명: `Array.prototype.fill()` 메소드는 배열의 모든 요소를 지정된 값으로 채웁니다. 이 메소드는 배열 자체를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.fill(0)
        ```
        
    - [ ]  Array.prototype.pop()
        
        설명: `Array.prototype.pop()` 메소드는 배열의 마지막 요소를 제거하고 반환합니다. 배열의 길이는 하나 줄어듭니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.pop()
        ```
        
    - [ ]  Array.prototype.indexOf()
        
        설명 : `Array.prototype.indexOf()` 메소드는 배열 안에서 원하는 값을 찾습니다. 이 메소드는 찾은 값의 인덱스를 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arr = [1, 2, 3, 4, 5];
        const result = arr.indexOf(3)
        ```
        
    - [ ]  Array.prototype.from()
        
        설명 : `Array.prototype.from()` 메소드는 유사 배열 객체 또는 반복 가능한 객체로부터 새로운 배열 인스턴스를 생성합니다. 이 메소드는 새로운 배열을 반환합니다.
        
        예제 코드:
        
        ```jsx
        const arrLike = {0: 'a', 1: 'b', length: 2};
        const result = Array.from(arrLike)
        ```
        
- [ ]  ECMAScript와 Javascript의 차이점에 대해 조사하기 (5문장 요약)
    
    ECMAScript와 Javascript는 많은 공통점이 있지만, 각각의 구별점도 있습니다. ECMAScript는 스크립트 프로그래밍 언어의 스펙이고, Javascript는 ECMAScript의 구현체 중 하나입니다. 따라서, ECMAScript는 모든 스크립트 언어의 기본이 되는 베이스 스펙이며, Javascript는 ECMAScript를 기반으로 만들어진 스크립트 언어라고 볼 수 있습니다. ECMAScript는 모든 스크립트 언어의 공통 요소를 포함하고 있고, Javascript는 ECMAScript의 기능을 향상시킨 기능과 특정 브라우저에 최적화된 기능들을 가지고 있습니다.
    
- [ ]  Javascript의 프로토타입에 대해 조사하기 (5문장 요약)
    
    Javascript의 프로토타입은 객체들이 상속을 통해 공통의 기능을 공유할 수 있는 메커니즘을 제공합니다. 객체는 다른 객체로부터 속성을 상속하기 위해 프로토타입 객체를 가집니다. 객체의 모든 프로토타입은 자신의 프로토타입을 갖고 있는 연결된 객체 계층을 만듭니다. 각 프로토타입은 객체 생성자에서 사용할 수 있는 메소드와 프로퍼티를 갖고 있습니다. 다른 객체로부터 상속받아 공유해야하는 기능을 프로토타입에 추가하면 객체 생성자에 공유되는 기능이 됩니다.
    
- [ ] #15
    
    Javascript의 클로저는 함수가 생성될 때 바깥 함수의 스코프 체인을 기억하는 기능을 제공합니다. 클로저는 특정 스코프의 변수들에 접근할 수 있는 범위를 제공합니다. 클로저를 통해 함수 내부에서 접근할 수 있는 변수들은 내부 함수가 생성될 때 바깥 함수의 스코프 체인에 있는 변수들입니다. 따라서, 클로저는 함수가 생성될 때 스코프 체인에 따라 변수들에 접근할 수 있는 범위를 제공합니다. 클로저는 자바스크립트에서 정보 은닉과 접근 제한을 가능하게 합니다.
    
- [ ]  Javascript의 스코프에 대해 조사하기 (5문장 요약)
    
    Javascript의 스코프는 실행 컨텍스트에서 변수와 함수를 참조할 수 있는 범위를 제공합니다. 스코프는 전역 스코프와 지역 스코프로 구분됩니다. 전역 스코프는 모든 스크립트가 실행되는 컨텍스트의 최상위 스코프로, 모든 함수가 접근할 수 있습니다. 그리고 지역 스코프는 함수 내부로 들어갈 때 마다 생성되는 개별 스코프로, 함수 내에서만 변수와 함수에 접근할 수 있습니다. 따라서, 함수를 통해 스코프를 변경하면 지역 스코프에 있는 변수들을 접근할 수 있게 됩니다.
    
- [ ]  Javascript의 this에 대해 조사하기 (5문장 요약)
    
    Javascript의 this는 함수 내에서 사용되는 참조 변수로, 객체의 메소드를 포함한 함수 내부에서 사용할 때 메소드가 속한 객체를 참조합니다. this는 함수가 실행될 때 실행 컨텍스트에 따라 달라집니다. this는 전역 스코프의 this와는 다르게, 함수 내부의 this는 실행 컨텍스트에 따라 다른 객체를 참조합니다. 또한, 화살표 함수는 this의 바인딩이 다른 일반 함수와 다르며, 일반 함수는 this 바인딩이 실행 컨텍스트에 따라 다르지만, 화살표 함수의 this는 함수가 생성될 때 상위 스코프의 this를 그대로 가져옵니다.
    
- [ ]  Javascript의 실행컨텍스트에 대해 조사하기 (10문장 요약)
    
    Javascript의 실행 컨텍스트는 스크립트 실행에 필요한 컨텍스트를 생성하는 데 사용됩니다. 실행 컨텍스트는 스크립트 실행을 위해 필요한 변수들의 메모리 공간과 스코프 체인을 생성하는데 사용됩니다. 실행 컨텍스트는 동작하기 위해 변수 선언, 함수 정의 및 함수 내 코드 실행 등의 단계를 거칩니다. 또한, 실행 컨텍스트는 스크립트 실행 시 변수들과 함수들의 스코프를 관리하는데 사용됩니다. 실행 컨텍스트는 변수들에 접근하기 위해 객체 계층 내부를 탐색해야 합니다. 실행 컨텍스트는 프로그램의 스코프 체인을 생성하고, 스코프 체인 내의 각 변수에 대해 메모리 공간을 할당합니다. 따라서, 스크립트 실행을 위해 함수 내에서 사용되는 변수들과 함수들은 실행 컨텍스트 내의 스코프 체인에 저장됩니다.
    
- [ ]  Javascript의 이벤트에 대해 조사하기 (5문장 요약)
    - [ ]  이벤트 위임
        
        Javascript의 이벤트는 사용자가 특정 객체에 마우스나 키보드를 사용하여 인터랙션을 할 때 발생합니다. 이벤트는 이벤트 리스너를 통해 인터랙션을 감지하고 이벤트 핸들러를 통해 이벤트에 맞는 동작을 처리합니다. 또한, 이벤트 위임은 이벤트를 부모 요소로부터 자식 요소까지 전달하는 기능입니다. 이벤트 위임을 통해 부모 요소에 하나의 이벤트 리스너로 모든 자식 요소들을 관리할 수 있습니다. 이벤트 위임을 사용하면 많은 이벤트 리스너를 등록하는 데 소모되는 리소스를 줄일 수 있습니다.
        
    - [ ]  이벤트 버블링
        
        Javascript의 이벤트 버블링은 이벤트가 부모 요소로부터 자식 요소까지 전파되는 것을 말합니다. 이벤트 버블링은 이벤트를 부모 요소 내부에서 자식 요소로 전달하는 방법으로, 자식 요소로부터 부모 요소까지 이벤트가 전파됩니다. 또한, 이벤트 버블링은 이벤트가 부모 요소에 도달하기 전에 이벤트가 자식 요소에서 취소될 수 있는 기회를 제공합니다. 따라서, 이벤트 버블링을 사용하면 부모 요소에 하나의 이벤트 리스너로 자식 요소들의 모든 이벤트를 관리할 수 있으며, 불필요한 이벤트 전파를 줄일 수 있습니다.
        
    - [ ]  이벤트 캡처링
        
        Javascript의 이벤트 캡처링은 이벤트가 부모 요소부터 자식 요소까지 전파되는 방법을 말합니다. 이벤트 캡처링은 이벤트가 부모 요소부터 자식 요소까지 전파되는 과정에서 부모 요소가 먼저 이벤트를 감지하며, 자식 요소가 이벤트를 감지하기 전에 부모 요소가 이벤트를 취소할 수 있는 기회를 제공합니다. 이벤트 캡처링을 사용하면 부모 요소가 먼저 이벤트를 감지하고, 자식 요소가 이벤트를 감지하기 전에 불필요한 이벤트 전파를 줄일 수 있습니다.

**Comment by JunilHwang** [comment]
채은님의 이슈에도 남겼던 질문들인데요,
호연님께서도 한 번 고민해보시면 좋을 것 같아요!

1. Javascript는 도대체 왜 Prototype이라는 개념을 사용한걸까요? 
2. React에서는 이 클로저가 어디서 이용되고 있을까요?
3. js에서 method와 function의 차이가 뭘까요?
```js
var num = 100;
function fn() {
  console.log(this.num);
}
const foo = { num: 1000 };
const bar = { num: 2000 };
foo.fn = fn;
bar.fn = foo.fn;

foo.fn(); // 1
bar.fn(); // 2
fn(); // 3

foo.fn === bar.fn; // 4
fn === foo.fn; // 5
fn === bar.fn; // 6
```
1 ~ 6에는 각각 어떤 값이 출력될까요?

4. 이벤트 버블링은, 어째서 버블링이라는 이름을 갖게 된걸까요?
5. 버블링 vs 캡처링 -> 어떤게 먼저 실행될까요?
