### ISSUE TITLE
[Step2] Vanilla Javascript로 무작정 TodoList 만들기 (김호준)

### ISSUE THREAD

**Issue by hojunkim02** [DKU-D-Coding/js-study-make-framework-lv1#18]
### Array.prototype.map()

배열의 요소를 순서대로 인자로 받아 주어진 함수를 호출한 후 새로운 배열을 반환한다.

```jsx
const array1 = [1, 4, 9, 16];

// Pass a function to map
const map1 = array1.map(x => x * 2);

console.log(map1);
// Expected output: Array [2, 8, 18, 32]
```

### Array.prototype.filter()

주어진 함수의 테스트를 통과하는 요소들을 모아 새로운 배열을 반환한다.

```jsx
const words = ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present'];

const result = words.filter(word => word.length > 6);

console.log(result);
// Expected output: Array ["exuberant", "destruction", "present"]
```

### Array.prototype.reduce()

요소를 순서대로 읽으며 축적값과 현재값을 인자로 받아 변형하여 마지막 축적값을 반환한다.

```jsx
const array1 = [1, 2, 3, 4];

// 0 + 1 + 2 + 3 + 4
const initialValue = 0;
const sumWithInitial = array1.reduce(
  (accumulator, currentValue) => accumulator + currentValue,
  initialValue
);

console.log(sumWithInitial);
// Expected output: 10
```

### Array.prototype.forEach()

무언가를 반환하는 메소드는 아니며, 요소를 순서대로 인자로 받아 주어진 함수를 호출한다.

```jsx
const array1 = ['a', 'b', 'c'];

array1.forEach(element => console.log(element));

// Expected output: "a"
// Expected output: "b"
// Expected output: "c"
```

### Array.prototype.some()

참 또는 거짓을 반환하며, 주어진 함수의 테스트를 적어도 하나라도 통과하면 참을 반환한다.

```jsx
const array = [1, 2, 3, 4, 5];

// Checks whether an element is even
const even = (element) => element % 2 === 0;

console.log(array.some(even));
// Expected output: true
```

### Array.prototype.every()

참 또는 거짓을 반환하며, 주어진 함수의 테스트를 모든 요소가 통과하면 참을 반환한다.

```jsx
const isBelowThreshold = (currentValue) => currentValue < 40;

const array1 = [1, 30, 39, 29, 10, 13];

console.log(array1.every(isBelowThreshold));
// Expected output: true
```

### Array.prototype.find()

주어진 함수의 테스트를 통과하는 첫 번째 요소를 반환한다.

```jsx
const array1 = [5, 12, 8, 130, 44];

const found = array1.find(element => element > 10);

console.log(found);
// Expected output: 12
```

### Array.prototype.findIndex()

주어진 함수의 테스트를 통과하는 첫 번째 요소의 인덱스를 반환한다.

```jsx
const array1 = [5, 12, 8, 130, 44];

const isLargeNumber = (element) => element > 13;

console.log(array1.findIndex(isLargeNumber));
// Expected output: 3
```

### Array.prototype.includes()

참 또는 거짓을 반환하며, 배열이 주어진 요소를 가지고 있다면 참을 반환한다.

```jsx
const array1 = [1, 2, 3];

console.log(array1.includes(2));
// Expected output: true

const pets = ['cat', 'dog', 'bat'];

console.log(pets.includes('cat'));
// Expected output: true

console.log(pets.includes('at'));
// Expected output: false
```

### Array.prototype.push()

배열의 끝에 하나 이상의 요소를 추가하고, 새로은 배열의 길이를 반환한다.

```jsx
const animals = ['pigs', 'goats', 'sheep'];

const count = animals.push('cows');
console.log(count);
// Expected output: 4
console.log(animals);
// Expected output: Array ["pigs", "goats", "sheep", "cows"]

animals.push('chickens', 'cats', 'dogs');
console.log(animals);
// Expected output: Array ["pigs", "goats", "sheep", "cows", "chickens", "cats", "dogs"]
```

### Array.prototype.splice()

배열의 요소를 변경한다. 변경을 시작할 인덱스, 삭제할 요소의 개수, 삽입할 요소를 받을 수 있다.

```jsx
const months = ['Jan', 'March', 'April', 'June'];
months.splice(1, 0, 'Feb');
// Inserts at index 1
console.log(months);
// Expected output: Array ["Jan", "Feb", "March", "April", "June"]

months.splice(4, 1, 'May');
// Replaces 1 element at index 4
console.log(months);
// Expected output: Array ["Jan", "Feb", "March", "April", "May"]
```

### Array.prototype.slice()

배열 중 일부를 반환한다. 필요한 배열의 시작 인덱스, 끝 인덱스를 받을 수 있다.

```jsx
const animals = ['ant', 'bison', 'camel', 'duck', 'elephant'];

console.log(animals.slice(2));
// Expected output: Array ["camel", "duck", "elephant"]

console.log(animals.slice(2, 4));
// Expected output: Array ["camel", "duck"]

console.log(animals.slice(1, 5));
// Expected output: Array ["bison", "camel", "duck", "elephant"]

console.log(animals.slice(-2));
// Expected output: Array ["duck", "elephant"]

console.log(animals.slice(2, -1));
// Expected output: Array ["camel", "duck"]

console.log(animals.slice());
// Expected output: Array ["ant", "bison", "camel", "duck", "elephant"]
```

### Array.prototype.shift()

배열의 첫 번째 요소를 제거하고 제거한 요소를 반환한다.

```jsx
const array1 = [1, 2, 3];

const firstElement = array1.shift();

console.log(array1);
// Expected output: Array [2, 3]

console.log(firstElement);
// Expected output: 1
```

### Array.prototype.unshift()

새로운 요소를 배열의 맨 앞에 추가하고 새로운 배열의 길이를 반환한디.

```jsx
const array1 = [1, 2, 3];

console.log(array1.unshift(4, 5));
// Expected output: 5

console.log(array1);
// Expected output: Array [4, 5, 1, 2, 3]
```

### Array.prototype.concat()

기존의 배열에 입력받은 배열을 합친 후 반환한다.

```jsx
const array1 = ['a', 'b', 'c'];
const array2 = ['d', 'e', 'f'];
const array3 = array1.concat(array2);

console.log(array3);
// Expected output: Array ["a", "b", "c", "d", "e", "f"]
```

### Array.prototype.join()

배열의 모든 요소를 연결하여 하나의 문자열을 반환한다.

```jsx
const elements = ['Fire', 'Air', 'Water'];

console.log(elements.join());
// Expected output: "Fire,Air,Water"

console.log(elements.join(''));
// Expected output: "FireAirWater"

console.log(elements.join('-'));
// Expected output: "Fire-Air-Water"
```

### Array.prototype.reverse()

순서가 반대인 배열을 반환한다.

```jsx
const array1 = ['one', 'two', 'three'];
console.log('array1:', array1);
// Expected output: "array1:" Array ["one", "two", "three"]

const reversed = array1.reverse();
console.log('reversed:', reversed);
// Expected output: "reversed:" Array ["three", "two", "one"]

// Careful: reverse is destructive -- it changes the original array.
console.log('array1:', array1);
// Expected output: "array1:" Array ["three", "two", "one"]
```

### Array.prototype.sort()

배열을 적절하게 정렬하여 반환한다.

```jsx
const months = ['March', 'Jan', 'Feb', 'Dec'];
months.sort();
console.log(months);
// Expected output: Array ["Dec", "Feb", "Jan", "March"]

const array1 = [1, 30, 4, 21, 100000];
array1.sort();
console.log(array1);
// Expected output: Array [1, 100000, 21, 30, 4]
```

### Array.prototype.flat()

중첩된 배열을 평탄화하여 (깊이 차이를 하나로 통일하여) 반환한다.

```jsx
const arr1 = [0, 1, 2, [3, 4]];

console.log(arr1.flat());
// Expected output: Array [0, 1, 2, 3, 4]

const arr2 = [0, 1, 2, [[[3, 4]]]];

console.log(arr2.flat(2));
// Expected output: Array [0, 1, 2, Array [3, 4]]
```

### Array.prototype.flatMap()

map 메소드를 실행 후 flat 메소드를 실행한다.

```jsx
const arr1 = [1, 2, [3], [4, 5], 6, []];

const flattened = arr1.flatMap(num => num);

console.log(flattened);
// Expected output: Array [1, 2, 3, 4, 5, 6]
```

### Array.prototype.fill()

배열의 어떤 구간을 특정 요소로 채울 수 있다. 특정 요소, 시작 인덱스, 끝 인덱스를 요소로 받는다.

```jsx
const array1 = [1, 2, 3, 4];

// Fill with 0 from position 2 until position 4
console.log(array1.fill(0, 2, 4));
// Expected output: Array [1, 2, 0, 0]

// Fill with 5 from position 1
console.log(array1.fill(5, 1));
// Expected output: Array [1, 5, 5, 5]

console.log(array1.fill(6));
// Expected output: Array [6, 6, 6, 6]
```

### Array.prototype.pop()

배열의 마지막 요소를 제거하고 그 배열을 반환한다.

```jsx
const plants = ['broccoli', 'cauliflower', 'cabbage', 'kale', 'tomato'];

console.log(plants.pop());
// Expected output: "tomato"

console.log(plants);
// Expected output: Array ["broccoli", "cauliflower", "cabbage", "kale"]

plants.pop();

console.log(plants);
// Expected output: Array ["broccoli", "cauliflower", "cabbage"]
```

### Array.prototype.indexOf()

주어진 요소에 따라 배열에서 발견된 첫 번째 요소의 인덱스를 반환하고, 존재하지 않으면 -1 을 반환한다.

```jsx
const beasts = ['ant', 'bison', 'camel', 'duck', 'bison'];

console.log(beasts.indexOf('bison'));
// Expected output: 1

// Start from index 2
console.log(beasts.indexOf('bison', 2));
// Expected output: 4

console.log(beasts.indexOf('giraffe'));
// Expected output: -1
```

### Array.from()

유사 배열 객체 또는 반복 가능 객체가 주어졌을 때 이를 얕게 복사하여 새로운 배열을 만든다.

```jsx
console.log(Array.from('foo'));
// Expected output: Array ["f", "o", "o"]

console.log(Array.from([1, 2, 3], x => x + x));
// Expected output: Array [2, 4, 6]
```

## ECMAScript와 Javascript의 차이점에 대해 조사하기 (5문장 요약)

1. ECMAScript 는 스크립트 언어를 위한 설명서이다.
2. 자바스크립트는 ES 규칙에 기반하여 개발되고 있는 프로그래밍 언어이다.
3. 브라우저 엔진에 따라 달라질 수 있는 자바스크립트를 표준화하기 위해 ES 규칙이 만들어졌다.
4. 하지만 ES 규칙을 따르는 언어는 JS 이외에도 액션스크립트나 J 스크립트 등의 구현체도 또한 존재한다.
5. 현재의 ECMAScript 는 대체로 자바스크립트 계열의 언어를 위해 업데이트되고 있다.

## Javascript의 프로토타입에 대해 조사하기 (5문장 요약)

1. 자바스크립트는 프로토타입을 통해 객체와 객체 간의 연결을 관리한다.
2. 프로토타입은 자바스크립트 객체가 가지고 있는 한 바구니이며, 별도로 정의하지 않는 한 비어 있는 상태이다.
3. 어떤 객체를 생성할 때, 원형 객체 속에 생성된 객체에서 사용할 수 있는 요소들을 미리 정의할 수 있다.
4. 이를 원형 객체, 즉 프로토타입 객체로부터 생성된 객체에 멤버들을 상속한다고 한다.
5. 이때, 원형 객체의 프로토타입 속성에 담겨 있는 요소들이 생성된 객체로 상속된다.

## Javascript의 클로저에 대해 조사하기 (5문장 요약)

1. 흔히 <패러다임> 이라는 말을 쓰곤 하는데, 이는 “위대한 연구와 그 방법론” 과 “그러한 방법을 통해 연구되는 연구 문화” 를 동시에 의미하며, 흔히 혼동되어 사용된다.
2. 자바스크립트에서의 클로저는 이와 비슷하게, “함수 내부의 폐쇄된 함수” 와 “그 함수를 이용할 수 있는 어휘적 범위” 를 동시에 의미하며, 이 또한 흔히 혼동되어 사용된다.
3. 클로저 함수란, 간단히 함수 내부에서 외부로 리턴되는 함수이다.
4. 클로저 함수가 리턴될 때, 그 함수와 같은 블럭에 존재하는 변수들은 수명이 끝나지 않고, 접근 가능하다.
5. 이러한 변수들은 클로저 함수를 통해 동적으로 사용될 수 있으며 이러한 체인을 클로저 체인이라 한다.

→ **사실 잘 모르겠어요! ㅠㅠ**

## Javascript의 스코프에 대해 조사하기 (5문장 요약)

1. 스코프는 의미 그대로 범위, 또는 영역을 의미한다.
2. 보다 구체적으로, 현재 실행되고 있는 코드의 영역으로서 같은 영역 내부에서 표현된 값들은 서로 참조될 수 있다.
3. 현대 프로그래밍 언어들에서 볼 때, 하나의 블럭을 같은 스코프로 볼 수 있다. (var 같은 애는 아님)
4. 스코프는 계층 형태로 되어 있어 하위 계층에서는 상위 계층의 값을 참조할 수 있지만 반대는 안 된다.
5. 자바스크립트의 경우 클로저와 같은 방법으로 블럭의 내부와 외부를 격리하여 스코프를 형성한다.

## Javascript의 this에 대해 조사하기 (5문장 요약)

1. 자바스크립트는 수많은 객체들의 조합이며, 상황에 따라 객체 내부에서 해당 객체에 접근해야 할 수도 있다.
2. 예를 들어, Hojun 이라는 객체에서 “여친 없는 기간” 에 “나이” 를 할당하고 싶을 수 있다.
3. 일반적인 프로그래밍 언어에서는 { noGFTerm: this.age } 와 같은 방식으로 함수의 맥락을 읽을 수 있다.
4. 자바스크립트의 일반 함수는 호출하는 방법에 따라 this 의 값이 달라진다.
5. 화살표 함수의 this는 일반 함수와 달리 무조건 자신을 감싼 범위를 가리킨다.

## Javascript의 실행컨텍스트에 대해 조사하기 (10문장 요약)

1. 자바스크립트 코드가 웹페이지에 존재한다고 해도, 내가 작성한 코드가 한 번에 전부 동작하는 것은 아니다.
2. 예를 들어 버튼을 눌렀을 때 숫자를 더하는 코드와 빼는 코드를 작성했다면, 당연히 두 코드는 동시에 동작해서는 안 된다.
3. 이렇게 코드들은 현재 “실행 가능한 코드” 들의 조합으로 이루어져 있는데, 이러한 추상적 개념을 실행 컨텍스트라 한다.
4. 전역 컨텍스트는 함수에서 실행되지 않는 나머지 코드들이며, window 객체를 this 로 할당하여 실행된다.
5. 함수 컨텍스트는 함수 내에서 실행되는 코드들이며, 함수가 호출되면 생성되고, 함수가 끝나면 소멸한다.
6. 실행 컨텍스트의 수명은 렉시컬 환경, 변수 환경 생성 → 호출 순서로 이루어진다.
7. 환경 생성 단계에서는 실제로 컴퓨터에게 필요한 값들을 매핑하여 컴퓨터가 알아듣는 코드로 변환한다.
8. 또한 브라우저는 컴퓨터는 코드를 읽으며 메모리에 실행 컨텍스트의 변수와 함수를 저장한다.
9. 실행 컨텍스트의 실행 단계에서는 코드가 LIFO 방식으로 실행된다.
10. 간략히, 전역 변수가 가장 먼저 셋팅 되어 가장 마지막에 실행된다고 볼 수 있다.

### 이벤트 위임

1. 바닐라 자바스크립트에서 자주 쓰이는 이벤트 핸들링 기법으로서, 상위 요소를 선택하여 하위 요소의 이벤트들까지 제어하는 방법이다.
2. 보통 어떤 요소의 동적 집단에 대해서 모든 요소에 대해 동일한 이벤트를 할당해야 할 경우에 대해 사용하게 된다.
3. 이벤트의 target 요소를 통해 어디서 출발한 이벤트인지 확인하여 사용할 수 있다.

### 이벤트 버블링

1. 특정 화면 요소에서 이벤트가 발생했을 때 해당 이벤트가 더 상위의 화면 요소들로 전달되어 가는 특성을 의미한다.
2. 예를 들어, 어떤 div와 그 내부의 button 둘 다 click 이벤트에 반응하는 이벤트 리스너를 등록했다고 하자.
3. 이후 button 을 클릭하여 이벤트를 발생시키면, div 와 button 에 둘 다 이벤트가 발생하게 될 것이다.
4. 이러한 경우 button 이 우선 이벤트가 발생하고, 이후 div 의 이벤트가 발생한다.

### 이벤트 캡처링

1. 이벤트 캡쳐링은 이벤트가 발생한 위치를 탐색하는 과정으로서, 버블링과는 반대 방향의 이벤트 전파이다.
2. 이벤트 리스너에 capture 를 설정하여 캡쳐 과정을 확인할 수 있다.

**Comment by hojunkim02** [comment]
클로저 부분부터 뭔가 조사하면 조사할수록 이해가 안 돼서... 좀 늦었습니다 ㅠ

**Comment by JunilHwang** [comment]
1. 그렇다면, 클로저가 React에서 언제 어떻게 어디서 사용되고 있을까요!?
2. 조사한 것들중 "원본 배열"을 조작하는 메소드는 어떤 것들이 있을까요?
3. push, pop과 shift, unshift 이렇게 두 그룹이 있는데, 성능차이가 어떻게 날까요?
