### ISSUE TITLE
[Step3] Component 구성하기 (전진우)

### ISSUE THREAD

**Issue by Jun-Jinu** [DKU-D-Coding/js-study-make-framework-lv1#20]
[노션링크](https://discreet-snowshoe-17f.notion.site/Step-3-Component-0136c07eb27644a2b585ca7575527b40)

- 이론 조사 내용도 점진적으로 수정하고 다듬고 글로 정리할 예정입니당
- 선택요구사항은 2월 8일기준 아직 수행하지 않았으나 시간나는대로 노션, 깃허브 파일에 추가해볼 예정입니다! 감사합니다😁

## 이론

- [x]  ES5의 Class와 ES6의 Class의 차이점에 대해 조사하기 (5가지)
- ES6에서 class 키워드를 활용해서 생성자 함수를 사용하고 객체 생성, 초기화가 가능합니다.
- ES5에서는 class 키워드가 존재하지 않습니다.
- 따라서 ES5에서는 function과 this 키워드를 통해서 객체를 다룰 수 있습니다.
- 또한 ES6에서 super 키워드와 프로토타입 체이닝을 활용해서 상속을 간편하게 구현할 수 있게 되었습니다.
- 즉, ES5에서 구현할 수 있는 내용을 ES6에서 class 키워드를 통해서 간편하게 구현할 수 있게된 것입니다.
- [x]  ES6의 Class만이 가지고 있는 특징과 장점에 대해 조사하기 (3가지)
- 특징으로는 class 키워드로 객체를 생성할때 프로토타입을 생성하고 문맥을 바인딩합니다.
- 이에따른 장점으로 레거시프로젝트에서 prototype으로 상속을 구현했을 경우에도 class를 사용할 수 있다는 것입니다.
- 또한 이렇게 변경한 ES6의 class는 ES5의 prototype을 활용한 상속보다 직관적이고 빠르게 상속을 구현할 수있습니다.
- [x]  객체지향 5대원칙에 대해 조사하기 (각각 5문장 요약)
    - [x]  SRP(Single Responsibility Principle)
    - 정의: 객체는 오직 하나의 책임을 가져야 한다. (객체는 오직 하나의 변경의 이유만을 가져야 한다.)
    - `모든 서비스는 단 하나의 책임을 수행하는 데 집중`되어야 한다는 원칙
    - 따라서 SRP 적용으로 인해서 다른 클래스들이 서로 영향을 미치는 연쇄작용을 줄일 수 있습니다.
    - 코드의 가독성 향상, 유지보수 용이라는 이점까지 누릴 수 있으며 다른 원칙들을 적용하는 기초가 됩니다
    - 다른 원칙들을 적용하는 기초가 됩니다.
    - [x]  OCP(Open-Closed Principle)
    - 객체는 확장에 대해서는 개방적이고 수정에 대해서는 폐쇄적이어야 한다는 원칙입니다.
    - 즉, 객체 기능의 확장을 허용하고 스스로의 변경은 피해야 한다.
    - 재사용 가능한 코드를 만들기위한 규칙입니다.
    - 이에 중요한 매커니즘은 추상화(Abstraction)와 다형성(Polymorphism)이라고 설명합니다.
    - 따라서 `본질적인 특징` 을 명확히 정의해서 상속하는 것이 핵심이라 할 수 있습니다.
    - [x]  LSP(Liskov Substitution Principle)
    - 자식 클래스는 언제나 자신의 부모 클래스를 **대체**할 수 있다는 원칙입니다.
    - 즉, 해당 객체를 사용하는 클라이언트는 상위 타입이 하위 타입으로 변경되어도, 차이점을 인식하지 못한 채 상위 타입의 퍼블릭 인터페이스를 통해 서브 클래스를 사용할 수 있어야 한다는 것입니다.
    - 자식 클래스가 부모 클래스를 대체하기 위해서는 부모 클래스에 대한 클라이언트의 가정을 준수해야 한다는 것을 강조합니다.
    - 대체 가능성을 결정해야 하는 것은 해당 객체를 이용하는 클라이언트임을 반드시 잊지 말아야 합니다.
    - 해당 추상화 레벨에 맞게 메소드를 오버라이딩 하는게 합리적일 것입니다.
    - [x]  ISP(Interface Segregation Principle)
    - 클라이언트에서 사용하지 않는 메서드는 사용해선 안 된다. 그러므로 인터페이스를 다시 작게 나누어 만든다.
    - 모든 클라이언트가 자신의 관심에 맞는 퍼블릭 인터페이스(외부에서 접근 가능한 메세지)만을 접근하여 불필요한 간섭을 최소화할 수 있습니다.
    - 기존 클라이언트에 영향을 주지 않은 채로 유연하게 객체의 기능을 확장하거나 수정할 수 있습니다.
    - 인터페이스 분리 원칙을 지킨다는 것은 어떤 구현체에 부가 기능이 필요하다면 이 인터페이스를 구현하는 다른 인터페이스를 만들어서 해결할 수 있습니다.
    - 인터페이스의 SRP라고 할 수 있습니다.
    - [x]  DIP(Dependency Inversion Principle)
    - 고수준 모듈은 저수준 모듈의 구현에 의존해서는 안 되며, 저수준 모듈이 고수준 모듈에 의존해야 한다는 것입니다.
    - 객체 지향 프로그래밍에서는 객체들 사이에 메세지를 주고 받기 위해 의존성이 생기는데, 의존성 역전의 원칙은 올바른 의존 관계를 위한 원칙에 해당됩니다.
    - 다르게는 interface를 적극적으로 활용하라는 의미로 해석될 수 있습니다.
    - 고수준 모듈: 입력과 출력으로부터 먼(비즈니스와 관련된) 추상화된 모듈
    - 저수준 모듈: 입력과 출력으로부터 가까운(HTTP, 데이터베이스, 캐시 등과 관련된) 구현 모듈
- [x]  다형성, 캡슐화, 추상화, 상속, 인터페이스 등에 대해 조사하기 (각각 5문장 요약)
    - [x]  다형성
    - 하나의 객체가 여러 가지 타입을 가질 수 있는 것을 의미합니다.
    - 따라서 다형성을 활용하면 기능을 확장하거나, 객체를 변경해야할 때 타입 변경 없이 객체 주입만으로 수정이 일어나게 할 수 있다.
    - 구현은 오버로딩, 오버라이딩, 함수형 인터페이스가 대표적이다.
    - 앞서 조사한 원칙중 OCP, DIP는 다형성을 기본으로한다.
    - 다형성을 잘 활용하면 코드의 중복을 줄이면서 변경과 확장에 유연한 객체 지향적인 코딩에 유용하다.
    - [x]  캡슐화
    - 서로 연관있는 속성과 기능들을 하나의 캡슐로 만들어 데이터를 외부로부터 보호하는 것을 말합니다.
    - 캡슐화하는 이유로는 데이터 보호, 데이터 은닉이 있습니다.
    - 이를 구현하기 위해서 접근제어자(private 등)을 활용할 수 있습니다. (멘토님이 말씀하셨던 js에서 #도 이에 포함될듯합니다!)
    - 또한 getter, setter 등의 메서드도 캡슐화의 구현 방법입니다.
    - 이를 통해서 각 객체의 자율성을 높이고 결합도를 낮추어 객체 지향의 이점을 잘 살릴 수 있습니다.
    - [x]  추상화
    - 객체의 공통적인 속성과 기능을 추출하여 정의하는 것을 말합니다.
    - 자바에서는 추상 클래스, 인터페이스 등으로 구현합니다.
    - 인터페이스에 추상 메서드나 상수로 어떤 객체가 수행해야 하는 핵심적인 역할만을 규정해둡니다.
    - 그리고 실제 구현은 해당 인터페이스를 구현하는 각각의 객체들에서 하도록 설계하는 것을 의미합니다.
    - 즉, 역할과 구현의 분리입니다.
    - [x]  상속
    - 기존의 클래스를 재활용하여 새로운 클래스를 작성하는 것입니다.
    - 따라서 상위 클래스로부터 확장된 여러 하위 클래스들이 모두 상위 클래스의 속성과 기능을 간편하게 사용할 수 있습니다.
    - 이는 반복적인 코드를 최소화하고 공유하는 속성과 기능에 간편하게 접근하여 사용할 수 있도록 합니다.
    - 물론 일일히 변경하지 않아도 되므로 유지 보수에도 유리합니다.
    - 인터페이스를 활용한 구현보다는 추상화의 정도가 낮다고 할 수 있습니다.
    - [x]  인터페이스
    - 클라이언트 프로그램에 어떤 메서드를 제공하는지 알려주는 명세 또는 약속입니다.
    - 즉, 추상 메서드의 집합이라 할 수 있습니다.
    - 다만 추상클래스와의 차이점은 인스턴스 변수를 가질 수 없다는 것입니다.
    - 다중 상속이 가능하고 여러 인터페이스를 상속받을 수 있습니다. 이를 타입 상속(type inheritance)라 합니다.
    - 인터페이스 사용을 통해서 조작 및 변경 용이, 표준화 등의 장점이 있습니다.
- [x]  MVC Pattern, MVVM Pattern 등에 대해 조사하기 (각각 5문장 요약)
    - [x]  MVC
    - MVC (모델-뷰-컨트롤러) 는 사용자 인터페이스, 데이터 및 논리 제어를 구현하는데 널리 사용되는 소프트웨어 디자인 패턴입니다.
    - 소프트웨어의 비즈니스 로직과 화면을 구분하는데 중점을 두고 있습니다.
    - MVC는 각각 데이터와 비즈니스 로직 관리, 레이아웃과 화면 처리, 명령을 모델과 뷰 부분으로 라우팅합니다.
    - 어떻게 나누어야 하는가에 대한 답 중 하나라고 할 수 있습니다.
    - 분리되어 각 역할에 집중하게 함으로써 유지보수, 확장성, 유연성, 중복코딩 방지를 위한 해답 중 하나입니다.
    - [x]  MVVM
    - MVVM 패턴은 Model + View + View Model를 합친 용어입니다.
    - View Model은 View를 나타내 주기 위한 Model이자 View를 나타내기 위한 데이터 처리를 하는 부분입니다.
    - Command 패턴과 Data Binding을 이용하여 View와 View Model 사이의 의존성을 없앴습니다.
    - 각각의 부분은 독립적이기 때문에 모듈화 하여 개발할 수 있습니다.
    - MVVM 패턴의 단점은 View Model의 설계가 쉽지 않다는 점입니다.
- [x]  ESModule에 대해 조사하기 (5문장 요약)
    - ES6에 도입된 모듈 시스템입니다.
    - import, export를 사용해 다른 자바스크립트 파일끼리 서로 접근할 수 있습니다.
    - 브라우저에서 ES Module은 구성, 인스턴스화, 평가의 단계를 거쳐 동작합니다.
    - Node.js에서는 CommonJS가 있습니다.
    - ES Module에서는 라이브 바인딩을 사용한다. 따라서 순환 구조가 발생해도 빈 객체를 반환합니다. 하지만 CommonJS는 라이브 바인딩이 아니고 사본을 메모리에 넣기 때문에 사이클이 생기면 처리할 수 없습니다.
            
- [x]  가상돔에 대해 조사하기 (5줄 요약)
    - 실제 돔을 처리하지않고 가상돔과 메모리에서 미리 처리하고 저장해서 실제 돔과 동기화하는 프로그래밍 개념입니다.
    - 실제돔에 비교한 장점으로는 빠르다, 메모리 낭비가 덜하다 등을 이야기할 수 있습니다.
    - 그 이유로는 변화가 일어나면 변화 전, 후 가상돔과 비교해서 변화된 부분만 적용하기 때문입니다.
    - 즉, 전체를 재 렌더링할 필요가 없어지는 것입니다.
    - 다만 코드 길이가 길어지고 비교적 복잡해져 가독성이 나빠지므로 라이브러리 및 프레임워크가 이를 간편하게 해주는 역할을 하고있는것 같습니다.

**Comment by JunilHwang** [comment]
React와 Vue는 어떤 디자인 패턴을 사용하고 있을까요!?

**Comment by Jun-Jinu** [comment]
리액트가 View Model 레이어에 속하는 라이브러리라고 생각해서 MVVM 패턴을 사용하고 있다고 생각합니다

그리고 View에 대한 질문은 제가 이해를 못해서... View 중에서도 또 다른 디자인 패턴이 존재하는건지 궁금합니다.

**Comment by Jun-Jinu** [comment]
가상돔에 대한 조사도 추가했습니다!
