### ISSUE TITLE
[Step3] Component 구성하기 (김채은)

### ISSUE THREAD

**Issue by chchaeun** [DKU-D-Coding/js-study-make-framework-lv1#21]
## ES5의 Class와 ES6의 Class의 차이점에 대해 조사하기 (5가지)
- 생성자
	- ES5 - 함수를 new 연산자와 함께 호출했을 때 생성자 함수로써 동작하여 인스턴스를 생성할 수 있다. 
	- ES6 - class 키워드로 클래스를 선언하고 그 내부에 constructor 키워드로 생성자를 정의한다. 
- 스태틱 메서드
	- ES5 - 생성자 함수에 점 연산자를 통해 정의한다.
	- ES6 - 클래스 선언 블록 내부에 static 키워드로 선언한다.
- 프로토타입 메서드
	- ES5 - 생성자 함수에 .protytype.[method]로 정의한다.
	- ES6 - 클래스 선언 블록 내부에 선언하면 prototype 객체 내부에 할당된다.
- callable / non-callable
	- ES5 - new 연산자 없이 호출하면 함수 객체 내부 메서드 [[Call]]이 호출되어 일반함수로 호출된다.
	- ES6 - new 없이 호출하면 에러가 난다. 반드시 인스턴스를 생성한 후 호출해야 한다.
- 상속
	- ES5 - 상속을 위해 함수를 직접 구현해야 한다.
	- ES6 - extends, super 키워드로 상속을 간단하게 구현할 수 있다.

## ES6의 Class만이 가지고 있는 특징과 장점에 대해 조사하기 (3가지)
- class 블록 안에서 선언이 이뤄지기 때문에 prototype 문법으로 객체를 생성하는 것보다 직관적이고 가독성이 높다. 
- 하지만 내부 동작은 prototype을 기반으로 하기 때문에 메모리 절약 등의 이점을 취할 수 있다.
- 호이스팅되지만, Temporal Dead Zone으로 인해 선언 전에 참조하면 에러를 발생시킨다. 디버깅에 좀 더 용이하다.## 객체지향 5대원칙에 대해 조사하기 (각각 5문장 요약)

### SRP(Single Responsibility Principle)
- 단일 책임 원칙. 모든 클래스는 각각 하나의 책임만 가져야 한다. 클래스는 그 책임을 완전히 캡슐화해야 함을 말한다.
- 모듈이 변경되는 이유가 한가지여야 한다.
	- 해당 모듈이 여러 대상 또는 액터들에 대해 책임을 가져서는 안되고, 오직 하나의 액터에 대해서만 책임을 져야 한다.
- 단일 책임 원칙을 지키면 변경이 필요할 때 수정할 대상이 명확해진다. 시스템이 커지면서 서로 많은 의존성을 갖게 되면 수정시 서로 영향을 주지 않기 때문에 변화에 대응하기 쉽다.

### OCP(Open-Closed Principle)
- 개방-폐쇄 원칙. 확장에는 열려있고 수정에는 닫혀있어야 한다. 기존의 코드를 변경하지 않으면서 기능을 추가할 수 있도록 설계 되어야 한다.
- 개방 폐쇄 원칙을 지키기 위해서는 추상화에 의존해야 한다. 변하지 않는 부분은 고정하고 변하는 부분을 생략하여 추상화해서, 변경이 필요할 때 생략된 부분을 수정한다.

### LSP(Liskov Substitution Principle)
- 리스코프 치환 원칙. 자식 클래스는 언제나 자신의 부모 클래스를 대체할 수 있다. 부모 클래스가 들어갈 자리에 자식 클래스를 넣어도 계획대로 잘 작동해야 한다.
- 자식클래스는 부모클래스의 책임을 무시하거나 재정의하지 않고 확장만 수행하도록 해야 한다.
- 자식 클래스가 부모 클래스의 기존 메소드의 의미를 해치지 않는지 신중히 고민하고 올바르게 상속해야 한다.
### ISP(Interface Segregation Principle)
- 인터페이스 분리 원칙. 한 클래스는 자신이 사용하지 않는 인터페이스는 구현하지 말아야 한다. 하나의 큰 인터페이스를 상속 받기 보다는 인터페이스를 구체적이고 작은 단위들로 분리시켜 꼭 필요한 인터페이스만 상속해야 한다.
- 목적과 관심이 각기 다른 클라이언트가 있다면 인터페이스를 통해 적절하게 분리해줘야 한다. 클라이언트의 목적과 용도에 적합한 인터페이스만을 제공해야 한다.
- 모든 클라이언트가 자신의 관심에 맞는 퍼블릭 인터페이스만을 접근하여 불필요한 간섭을 최소화할 수 있다.
### DIP(Dependency Inversion Principle)
- 의존 역전 원칙. 의존 관계를 맺을 때 변화하기 쉬운 것 또는 자주 변화하는 것보다는 변화하기 어려운 것, 거의 변화가 없는 것에 의존해야 한다. 구체적인 클래스보다 인터페이스나 추상 클래스와 관계를 맺어야 한다.
- 고수준 모듈은 저수준 모듈의 구현에 의존해서는 안되며, 저수준 모듈이 고수준 모듈에 의존해야 한다.
	- 고수준 모듈: 입력과 출력으로부터 먼(비즈니스와 관련된) 추상화된 모듈
	- 저수준 모듈: 입력과 출력으로부터 가까운(HTTP, 데이터베이스, 캐시 등과 관련된) 구현 모듈
- 비즈니스와 관련된 부분이 세부사항에는 의존하지 않아야 한다.

### 다형성
- 프로그램 언어 각 요소들(상수, 변수, 식, 객체, 메소드 등)이 다양한 자료형(type)에 속하는 것이 허가되는 성질이다. 
- 예) 숫자->문자열 변환 함수, 날짜->문자열 변환 함수를 toStringFromNumber, toStringFromData처럼 따로 만들지 않고 toString으로 다양한 형태의 인자에 대해 한번에 처리할 수 있는 것 (오버로딩)
- 다형성을 구현하는 방법에는 오버로딩, 오버라이딩, 함수형 인터페이스가 있다.
- 오버로딩: 여러 종류의 타입을 받아들여 같은 기능을 하도록 만드는 것
- 오버라이딩: 상위 클래스의 메소드를 하위 클래스에서 재정의
### 캡슐화
- 객체의 속성과 행위를 하나로 묶고, 실제 구현 내용 일부를 외부에 감추어 은닉한다. 
- 클래스 안에 데이터와 데이터를 처리하는 행위를 묶고 외부에는 그 행위를 보여주지 않는 것
- 객체에서 내부 데이터를 꺼내와서 처리하는 게 아니라, 객체에게 처리할 행위를 요청하게 된다.
- 캡슐화를 이용하면 외부의 잘못된 사용으로 인해 객체가 손상되는 일을 막을 수 있다.
- 캡슐화된 멤버를 노출할지 숨길 것인지 결정하기 위해 접근제한자를 사용한다.
### 추상화
- 복잡한 자료, 모듈, 시스템 등으로부터 핵심적인 개념 또는 기능을 간추려 내는 것이다.
- 클래스를 정의할 때 불필요한 부분들을 생략하고 객체의 속성 중 중요한 것에만 중점을 두어 개략화한다.
- 제어 추상화: 메소드의 작동 방식과 같은 내부 로직을 숨기하는 것
- 데이터 추상화: 대상을 간단한 개념으로 일반화하는 과정
### 상속
- 자식 클래스가 부모 클래스의 멤버를 물려받는 것이다.
- 기존의 클래스(부모)에 기능을 추가하거나 재정의하여 새로운 클래스(자식)를 정의한다.
- 상속 대상은 부모의 필드와 메소드이다.
- 상속은 코드 중복을 줄여주고, 재사용성을 높인다. 유지 보수를 편리하게 해준다.

### 인터페이스
- 상수와 추상메소드만 존재하는 추상클래스. 일반 속성 및 메서드를 정의할 수 없다. 
- 선언된 인터페이스의 메소드는 상속받은 일반 클래스에서 반드시 전부 구현되어야 한다.
- 상속과 다르게 여러가지 인터페이스를 구현할 수 있다. 하나의 클래스가 두개 이상의 인터페이스를 구현할 수 있다.
- 최소한의 수정을 통해 변화에 대응할 수 있도록 한다.

### MVC
- 사용자 인터페이스로부터 비즈니스 로직을 분리한다.
- 컨트롤러가 비즈니스 로직을 수행해서 화면에 출력할 데이터 결과값을 모델에 넘겨주면 뷰는 모델에 있는 데이터를 참보해서 화면 렌더링 로직을 만든다.
- 뷰가 모델을 사용해야 하기 때문에 뷰와 모델의 의존성이 높다.
- 규모가 커지면 컨트롤러에 다수의 모델과 뷰가 복잡하게 연결돼있는 상황이 발생할 수 있다.
### MVVM
- 뷰와 모델 사이의 의존성을 낮춘 디자인 패턴이다.
- 사용자의 입력값이 뷰를 통해 들어오면 뷰모델에 전달되고, 모델에게 데이터를 요청한다. 모델이 응답하면 뷰모델이 값을 받아 가공처리하여 저장하고, 뷰가 데이터를 받아 화면에 표출한다.
- 뷰 모델은 뷰를 표현하기 위한 존재이다. 모델을 작동하기 위한 명령을 나타내고, 뷰의 상태를 유지시키고 뷰의 이벤트를 활성화한다.

## ESModule에 대해 조사하기 (5문장 요약)
- ES6에 도입된 모듈 시스템으로, import, export를 사용해 분리된 자바스크립트 파일끼리 서로 접근할 수 있게 하는 것이다.
- ESM 이전에는 각각 script 파일을 전역 스코프처럼 사용했다. 하지만 파일 순서가 뒤틀리면 에러가 발생하고, 하위스크립트가 상위 스크립트 값을 변경시키는 등 유지보수의 어려움이 있었다.
- 브라우저에서 ESModule은 구성, 인스턴스화, 평가 단계를 거쳐 동작한다.
	- 구성: entry파일부터 import문을 찾아가며 필요한 모든 파일을 모듈 레코드로 구문 분석한다.
	- 인스턴스화: export된 값을 모두 배치하기 위한 메모리 공간을 찾는다. Export와 import들이 이런 메모리 공간을 가리키도록 한다. 이 과정은 메모리 공간을 찾고 지정할 분 실제 값을 채우진 않는다
	- 평가: 코드를 실행하여 메모리를 변수의 실제값으로 채운다.

## 가상돔에 대해 조사하기 (5줄 요약)
- 웹 브라우저 단에서 dom 변화가 일어나면 웹 브라우저가 css를 다시 연산하고, 레이아웃을 구성하고, 페이지를 리페인트하는 과정이 여러번 반복하여 발생할 수 있고 이로 인해 성능 저하 또는 버그가 발생할 수 있다.
- 가상돔은 실제 돔에 접근하여 조작하는 대신, 이것을 추상화시킨 자바스크립트 객체를 사용하는 것이다.
- 데이터가 업데이트 되면 전체 ui를 가상돔에 리렌더링하고, 변화 전의 가상돔과 변화된 가상돔을 비교한 뒤 바뀐 부분만 실제 돔에 적용한다.

**Comment by JunilHwang** [comment]
> 가상돔은 실제 돔에 접근하여 조작하는 대신, 이것을 추상화시킨 자바스크립트 객체를 사용하는 것이다.

이 때의 제일 큰 이점은 무엇일까요!?
