### ISSUE TITLE
[Step3] Component 구성하기 (김호준)

### ISSUE THREAD

**Issue by hojunkim02** [DKU-D-Coding/js-study-make-framework-lv1#23]
## ES5의 Class와 ES6의 Class의 차이점에 대해 조사하기 (5가지)

1. 일반적인 객체 지향 프로그래밍 언어라면, class 를 사용한 객체의 활용이 익숙할 것이다.
2. 하지만 ES6 이전의 javascript 에는 기본 기능으로 class 가 탑재되어 있지 않았다.
3. 대신 생성자 함수를 만들어 프로토타입 기반의 객체 지향 프로그래밍을 하였다.

```jsx
function Animal(name) {
  this.name = name;
}

Animal.prototype.speak = function() {
  console.log(this.name + " makes a sound.");
};
```

1. ES6 이후에는 class 기능이 탑재되어 생성자, 메소드 등을 통해 보다 깔끔하고 편리해졌다.

```jsx
class Animal {
  constructor(name) {
    this.name = name;
  }

  speak() {
    console.log(`${this.name} makes a sound.`);
  }
}
```

1. 이러한 표현 방법은 여타 언어들의 class 와 유사해 보이지만 내부적으로는 프로토타입에 기반하여 동작하고 있기 때문에 prototype 을 통해 객체에 접근할 수 있다.

## ES6의 Class만이 가지고 있는 특징과 장점에 대해 조사하기 (3가지)

1. ES6 의 class 에는 일반적으로 class 문법에서 사용할 수 있는 생성자, 메소드, 상속 등의 문법을 지원하며 객체의 사용에 있어서 깔끔하게 관리할 수 있다.
2. Javascript 객체의 특징으로서, prototype 메소드를 사용할 수 있다.
3. 기존의 객체 생성 방식과 달리, ES6 의 클래스는 가독성과 유지보수에 있어서 더 유리하다.

### SRP(Single Responsibility Principle)

1. 단일 책임 원칙은 프로그램에서 클래스나 모듈이 변경될 수 있는 단 하나의 이유만을 가져야 한다고 명시하고 있다.
2. 즉, 클래스나 모듈은 프로그램에서 기능의 한 부분만을 담당해야 하는데 이는 코드의 복잡성이 줄어들고 이해, 유지 관리 및 확장을 용이하게 한다.
3. 또한 SRP 는 클래스의 책임에 대해 더 신중하게 생각하여 더 작고 단순한 부분으로 나눌 것을 권장하고 있다.

### OCP(Open-Closed Principle)

1. 개방-폐쇄 원칙은 클래스 또는 모듈은 확장을 위해서는 열려 있어야 하지만 수정을 위해서는 닫혀 있어야 한다고 명시하고 있다.
2. 즉, 클래스나 모듈은 기존 코드를 수정할 필요 없이 새로운 기능을 추가하기 위해 확장될 수 있는 방식으로 설계되어야 하는데, 이는 코드 변경으로 인해 기존 기능이 손상되는 것을 막고 유지 관리와 기능 확장을 용이하게 한다.
3. 또한 OCP 는 기존 코드를 수정하는 대신 상속이나 인터페이스를 통해 새로운 기능을 추가할 수 있는 방식으로 클래스와 모듈을 설계하도록 권장하고 있다.

### LSP(Liskov Substitution Principle)

1. 리스코프 치환 원칙은 슈퍼클래스의 객체가 프로그램의 정확성에 영향을 미치지 않고 서브클래스로 대체될 수 있어야 한다고 명시하고 있다.
2. 이는 어떤 객체들이 해당 클래스의 하위 클래스의 객체들로 대체되어도 프로그램이 문제 없이 작동할 수 있어야 함을 의미한다.
3. LSP 는 개발자들이 예측 가능하고 일관된 방식으로 클래스와 객체를 설계하도록 권장하고 있다.

### ISP(Interface Segregation Principle)

1. 인터페이스 분리 원칙은 클래스가 사용하지 않는 인터페이스를 강제로 구현해서는 안 된다고 명시하고 있다.
2. 즉, 클래스는 해당 동작과 관련된 메서드만 구현해야 한다는 것인데, 이는 코드의 복잡성을 줄이고 이해, 유지 및 확장을 용이하게 한다.
3. ISP 는 코드를 지나치게 광범위하거나 일반적인 것이 아니라 세밀하고 구체적인 방법으로 인터페이스를 설계하도록 권장하고 있다.

### DIP(Dependency Inversion Principle)

1. 의존관계 역전 원칙은 높은 수준의 모듈이 낮은 수준의 모듈에 의존해서는 안 되며, 둘 다 추상화에 의존해야 한다고 명시하고 있다.
2. 이는 클래스가 구체적인 표현이 아니라 추상화에 의존하고 있어야 한다는 것으로, 이러한 방식을 통해 클래스 간의 연결을 줄이고 코드를 보다 유연하게 유지할 수 있다.
3. DIP 는 클래스와 모듈을 긴밀하게 연결하지 않고 느슨하게 결합하는 방식으로 코드를 설계하도록 권장하고 있다.

### 다형성

1. 다형성은 서로 다른 클래스의 객체를 공통 클래스의 객체로 취급할 수 있도록 하는 객체 지향 프로그래밍의 개념이다.
2. 다형성은 프로그램 내에서 오버라이딩과 오버로딩을 통해 수행된다.
3. 오버라이딩을 사용하면, 하위 클래스는 상위 클래스에 정의된 메소드의 자체적 구현을 할 수 있다.
4. 오버로딩을 사용하면, 전달된 인수의 수와 유형에 따라 단일 메서드가 다양한 구현을 가질 수 있다.
5. 이러한 방식의 사용으로서 코드 재사용, 유지 관리, 가독성, 유연성 측면에서 향상된 코드를 작성할 수 있다.

### 캡슐화

1. 캡슐화는 코드의 다른 부분에서 클래스 내부의 세부 정보를 숨기고 클래스와 상호 작용하기 위해 공용 인터페이스를 노출하는 객체 지향 프로그래밍의 개념이다.
2. 캡슐화는 클래스의 데이터를 단일 단위 또는 객체로 래핑하는 것으로 수행된다.
3. 이러한 방식은 데이터 수정을 위한 접근에 대해 보다 안전하고 제어된 방식을 제공한다.
4. 이는 객체 내부 상태를 외부 간섭으로부터 보호하고 공용 인터페이스를 통한 접근만을 허용하도록 한다.
5. 캡슐화는 정보 은닉, 보안, 모듈성, 결합 감소 측면에서 향상된 코드를 작성할 수 있도록 한다.

### 추상화

1. 추상화는 구현 세부 정보를 숨기고 필수 기능만 사용자에게 노출하도록 하는 객체 지향 프로그래밍의 개념이다.
2. 이는 세부 정보를 숨기고 일반적인 동작만을 노출하는 것으로 복잡한 프로그램을 단순하게 만들어준다.
3. 추상화는 핵심적인 정보에만 집중하고 외적인 정보는 무시하는 것으로 시스템의 복잡도를 줄이는 데에 도움을 준다.
4. 추상화는 시스템 단순화, 재사용성, 유지 보수, 모듈식 설계에 있어서 향상된 코드를 작성할 수 있도록 한다.

### 상속

1. 상속은 한 클래스가 다른 클래스의 속성과 특징을 상속받을 수 있도록 하는 객체 지향 프로그래밍의 개념이다.
2. 이는 이미 존재하는 클래스를 기반으로 새로운 클래스를 만들 때 사용되며, 새로운 클래스는 기존 클래스의 특징과 메서드를 상속한다.
3. 상속을 통해 클래스는 계층 구조로 구성할 수 있으며, 일반적인 클래스로부터 보다 구체적인 클래스를 만들 수 있다.
4. 상속은 코드 재사용, 유지 관리, 가독성, 모듈식 설계에 있어서 향상된 코드를 작성할 수 있도록 한다.

### 인터페이스

1. 인터페이스는 특정 객체에게 할 수 있는 요청을 의미하며, 구현 클래스에 요청을 전달하는 프로토콜과 같은 개념이다.

### MVC

1. MVC 디자인 패턴은 서로 다른 로직을 수행하는 세 가지 구성요소가 상호작용하는 형태의 디자인 패턴이다.
2. Model 은 데이터 구조를 정의하고 조작한다.
3. View 는 유저에게 데이터를 보여주는 레이아웃을 관리한다.
4. Controler 는 Model 과 View 사이에서 유저의 입력을 통해 Model 과 View 를 효과적으로 업데이트한다.
5. MVC는 현재까지도 가장 흔하게 사용되는 디자인 패턴으로, 유연하고 효과적으로 서비스를 구성할 수 있도록 한다.

### MVVM

1. MVVM 디자인 패턴은 MVC 디자인 패턴의 변형된 형태로서, Controller 대신 ViewModel 을 사용한다.
2. 기존의 Controller 와 달리 ViewModel 은 데이터 바인딩을 통해 View 를 자동으로 업데이트한다.
3. 이러한 방식은 프로젝트 내부의 요소 사이를 중개하는 코드를 없애주기 때문에, ViewModel 에는 오직 View 에 관한 로직만을 작성할 수 있어 보다 정리된 느낌을 준다.
4. 기존의 MVC 형태에서는 View 의 출력에 대한 테스트를 하기 어려웠지만, ViewModel 의 사용은 이를 용이하게 해 준다.
5. MVVM 방식은 주로 안드로이드 개발에서 사용되는 중이다.

## ESModule에 대해 조사하기 (5문장 요약)

1. ES module 은 Javascript 에서 코드를 조직하고 재사용하는 방법이다.
2. ES module 은 함수, 객체, 변수를 파일마다 분산하여 저장할 수 있으며, import, export 를 통해 사용될 수 있다.
3. 이러한 방법은 기존의 CommonJS 모듈과 유사하지만, ES module 은 정적으로 분석되기 때문에 컴파일 시에 바로 결정되어 더 좋은 성능을 낼 수 있다.
4. CommonJS 와 달리 순환 종속성이 허용되기 때문에 모듈의 반복적 사용에 용이하며, 이해하기 편하다.
5. JS 프로젝트가 점점 복잡해짐에 따라 ES module 은 프로젝트를 만들고 유지보수하기 편리하게 만들어준다.

## 가상돔에 대해 조사하기 (5줄 요약)

1. 가상돔은 modern 자바스크립트 라이브러리에서 사용되는 컨셉으로, single-page application 을 만들 때 사용된다.
2. SIP 에서, UI 에 어떤 변화가 있을 때 마다 실제 DOM 을 변형시키면, 브라우저는 현재 화면을 전부 다시 그리기 떄문에 필요에 비해 비교적 큰 자원을 소모한다.
3. 가상돔은 UI 를 업데이트하는 중개 역할로서, 실제 변화해야 하는 최소한의 UI 만을 업데이트 하도록 한다.
4. 가상돔이 렌더를 최적화 하는 방법으로는, 실제 DOM 을 자바스크립트 객체로 복사하여 실제로 다시 랜더되어야 할 부분을 코드 상에서 미리 파악하는 방법을 사용하고 있다.
5. 자바스크립트 객체간의 비교는 실제 DOM 간의 비교보다 훨씬 가벼운 작업이기 때문에 웹사이트 성능에 긍정적인 영향을 주지만, 유저는 웹페이지의 첫 로드 시 가상 DOM 을 만드는 프로그램까지 로드해야 한다는 단점도 존재할 수 있다.

**Comment by JunilHwang** [comment]
> Javascript 객체의 특징으로서, prototype 메소드를 사용할 수 있다.
이건 class의 특징? 이라고 보긴 힘들 것 같아요! js의 특징이라서요!

> MVVM 방식은 주로 안드로이드 개발에서 사용되는 중이다.
그렇다면, 프론트엔드 프레임워크들은 어떤 패턴을 사용중일까요?

> 가상돔
렌더링 최적화 측면 말고, 다른 측면에서 가상돔을 쓰는 의의가 있을까요?
