### ISSUE TITLE
[Step4] 옵저버 패턴 학습

### ISSUE THREAD

**Issue by chchaeun** [DKU-D-Coding/js-study-make-framework-lv1#25]
# 4주차
## Observer Pattern
- 객체의 상태 변화를 관찰하는 관찰자들, 옵저버들의 목록을 객체에 등록하여 상태 변화가 있을 때마다 메서드 등을 통해 객체가 직접 목록의 각 옵저버에게 통지하도록 하는 디자인 패턴
- 어떤 객체의 상태가 변할 때 그와 연관된 객체들에 알림을 보낸다.
- 구독자가 어떤 주제를 구독하면, 주제가 발행됐을 때 구독자에게 알림을 보낸다.
- 느슨한 결합
	- 두 객체가 느슨하게 결합되어 있다는 건, 둘이 상호작용을 하긴 하지만 서로에 대해 잘 모르는 것
	- 옵저버 패턴에서는 주제와 옵저버가 느슨하게 결합되어 있는 객체 디자인을 제공
	- 주제가 옵저버에 대해 아는 것은 옵저버가 특정한 인터페이스를 구현한다는 것뿐이다. 옵저버가 무엇을 하는지는 알 필요가 없다.
	- 주제와 옵저버는 서로 독립적으로 재사용할 수 있다.
	- 주제나 옵저버가 바뀌더라도 서로에게 영향을 미치지 않는다.

## Object API
- Object.defineProperty()
	- 객체에 새로운 속성을 직접 정의하거나 이미 존재하는 속성을 수정한 후 해당 객체를 반환한다.
		- value: 속성에 설정할 값
		- writable: 속성을 수정할 수 있는지 여부
- Object.defineProperties()
	- 속성 여러 개를 정의할 수 있다.

```
const obj = {};
Object.defineProperty(obj, {
	prop1: {
		value: 1,
		writable: true,
	}
});

Object.defineProperties(obj, {
	prop2: {
		value: { a: 'a' },
		writable: false,
	},
	prop3: {
		value: '123',
		writable: true,
	}
});

console.log(obj);
```

## Proxy API
- 객체에 대한 기본 작업을 가로채고 재정의한다.
- target: 프록시할 원본 객체
- handler: 가로채는 작업과 가로채는 작업을 재정의하는 방법을 정의하는 객체
	- `get` 트랩은 target의 프로퍼티를 읽을 때, `set` 트랩은 target의 프로퍼티를 쓸 때 활성화된다.
- 객체를 읽거나 쓸 때 검증을 위해 사용한다.

**Comment by chchaeun** [comment]
실습하기 전에 했었는데 정리만 해놓고 깜빡하고 안올렸네요!

**Comment by JunilHwang** [comment]
> 느슨한 결합

1. 느슨한 결합을 해야 하는 이유가 뭘까요?
2. React에서 혹은 우리가 사용하는 라이브러리나 프레임워크에서 이렇게 느슨한 결합으로 쓰이는 경우가 또 어떤 것들이 있을까요?

> Proxy API vs Object.defineProperty

Proxy API로만 해결할 수 있는 문제가 있을까요?
