### ISSUE TITLE
[Step4] 옵저버 패턴 학습 (전진우)

### ISSUE THREAD

**Issue by Jun-Jinu** [DKU-D-Coding/js-study-make-framework-lv1#27]
## 이론
- [x]  Observer Pattern에 대해 조사하기 (10문장) - 구독자, 구독, 발행 등의 키워드를 사용
    - 구독자란? 관찰 대상 객체의 상태 변화를 관찰하는 객체
    - 구독이란? 구독자가 관찰 대상 객체의 상태 변화를 하는 과정
    - 발행이란? 관찰 대상 객체의 상태가 변화하면 등록된 구독자들에게 알림을 보내는 과정
    - 객체의 상태변화를 위한 관찰자(Observer)
    - 옵저버들의 목록을 객체에 등록해서 상태 변화가 있을 경우 메서드를 통해서 객체가 직접 목록의 각 옵저버에게 통지하도록 하는 디자인 패턴
    - 분산 이벤트 핸들링 시스템을 구현하는 데 사용
    - 발행-구독 패턴이라고 불림
    - 이 패턴은 관찰 대상 객체, 관찰자 객체 사이의 일대다 의존성을 정의함
    - 쓰는 이유는 객체간의 결합도를 낮추기 위해서 사용하므로 객체간의 의존성을 줄일 수 있음
    - 다만 너무 많이 사용하게 되면 상태 관리가 힘들어 짐
- [x]  Javascript Object API 조사하기
    - [x]  Object.defineProperty
        - 객체 속성을 정의하거나 수정하는 메소드.
        - 객체 속성을 정의할 때 기존의 속성값을 수정하거나, 새로운 속성값을 추가하는 데 사용됨.
        - 속성은 value, writable, enumerable, configurable, get, set 이 있다.
        - 예시 코드
        
        ```jsx
        const obj = {};
        
        Object.defineProperty(obj, "name", {
          value: "Jinu",
          writable: false,
          enumerable: true,
          configurable: false
        });
        ```
        
        - 해당 메소드를 쓰면 객체 속성에 대한 제약사항을 설정할 수 있으므로 객체의 안정성과 보안성을 높일 수 있다.
    - [x]  Object.defineProperties
        - 상단의 defineProperty에서 속성을 여러개 정의할 수 있다.
        - 예시코드
        
        ```jsx
        const obj = {};
        
        Object.defineProperties(person, {
          firstName: {
            value: 'Jinu',
            writable: true,
          },
          lastName: {
            value: 'Jun',
            writable: true,
          },
        });
        ```
        
- [x]  Javascript Proxy API 조사하기
    - 객체에 접근하려는 모든 요청을 가로채서 로직을 처리할 수 있다.
    - ‘new Proxy(target, handler)’로 이루어진다.
    - target은 프록시 객체로 가로챌 대상 객체를 의미한다.
    - handler는 프록시 객체가 호출될 때 실행할 메소드들을 정의한 객체이다.
    - 예시코드
    
    ```jsx
    let target = {
      name: 'Jinu',
      age: 26
    };
    
    let handler = {
      get: function(target, property) {
        console.log(`Getting ${property}!`);
        return target[property];
      }
    };
    
    let proxyObj = new Proxy(target, handler);
    
    console.log(proxyObj.name);
    ```

**Comment by JunilHwang** [comment]
Object.defineProperty나 Object.defineProperties 대신 proxy를 꼭 써야만 하는 상황이 있을까요?
반대로, 꼭 Object.defineProperty를 써야 하는 상황은 어떤 상황일까요?

유사한 API가 존재할 때 이런 비교를 잘 해보시면 좋답니다!
