### ISSUE TITLE
[Step1] 프레임워크에 대한 이해(전진우)

### ISSUE THREAD

**Issue by Jun-Jinu** [DKU-D-Coding/js-study-make-framework-lv1#4]
#노션 링크: https://discreet-snowshoe-17f.notion.site/1-2c21f542403f42ecbb114a94c164c2a0

### 브라우저, HTTP Protocal, HTML 등의 연관성에 대해 조사하기 (5문장 요약)

- 브라우저는 인터넷을 통해서 웹 서버에서 HTTP 프로토콜을 통해 쌍방향으로 통신합니다.
- 브라우저는 HTML문서를 화면에 보여주는 역할을 하는 프로그램입니다.
- HTTP 프로토콜은 문서의 리소스를 가져올 수 있게 해줍니다.
- 브라우저는 HTML 파일을 가지고 사용자에게 화면을 보여줍니다. 즉, 미리 작성된 코드를 통해서 서비스를 이용할 수 있도록 합니다.

### DOM(Document Object Model) 조사하기 (3문장 요약)

- 웹 페이지 문서에 접근하기 위한 인터페이스입니다.
- 자바스크립트로 앞서 작성된 HTML, CSS 요소나 속성을 추가, 삭제, 수정을 하기 위해서 반드시 필요한 인터페이스입니다.
- 아래 사진과 같이 트리구조로 이루어져있고 필요한 노드에 접근하여 필요한 작업을 할 수 있습니다.

![W3C 표준 객체 모델](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/9ff5107b-127b-4a18-9e42-d08025c0c06d/Untitled.png)

W3C 표준 객체 모델

### BOM(Browser Object Model) 조사하기 (3문장 요약)

- 브라우저와 관련된 객체들의 집합.
- DOM보다 큰 단위이며 최상위 객체는 window객체입니다. 그 외에 location, navigator, history, screen, document 객체 모델이 있습니다.
- 자바스크립트가 아니라 웹브라우저가 제공하는 기능입니다.

### CSS(Cascading Style Sheet) 조사하기 (3문장 요약)

- 사용자가 브라우저에서 접하는 HTML 요소들의 모양을 제어하고 원하는 디자인을 사용하여 표현하는 역할을 합니다.
- 마크업 언어로 작성된 문서의 요소들을 설하명며 데 사용하는 스타일 시트 언어입니다.
- 캐스케이딩: 특정 요소와 일치하는 요소가 두 개 이상이면 어떤 것을 적용할 것인지 우선순위를 다루는 것입니다.

### Javascript 조사하기 (3문장 요약)

- ECMAScript 사용을 준수하는 객체 기반의 스크립트 프로그래밍 언어
- 웹 브라우저에 주로 사용(응용 프로그램의 내장 객체에도 접근 가능)
- 근래에 많이 쓰이는 분야는 클라이언트용 인터페이스

### ECMAScript 조사하기 (3문장 요약)

- ECMA-262 기술 규격에 의해 정의된 범용 스크립트 프로그래밍 언어
- 자바스크립트를 표준화하기위해  만들어진 프로그래밍 언어
- 사실상 자바스크립트를 기반으로하므로 밀접하게 연관된 언어
- ES5까지는 대부분의 브라우저와 호환되나 ES6이후로는 안되면 BABEL과 같은 트랜스컴파일러로 호환 가능

### Javascript Framework가 등장한 배경에 대해 조사하기 (5문장 요약)

- 기본적으로 초기웹은 현대에 비해서 코드 또한 복잡하게 작성되고 배우는 난이도가 높았습니다
- 이를 위한 해결책은 끊임없이 제시되었고 발전했습니다
- 1990년 JAVA가 등장하고 JSP로 동적인 웹페이지를 만들었고 사용자 요청을 받으면 서버에서 페이지 전체 html을 만드는 방식이었는데 너무 비효율적이었습니다
- 이를 해결하기 위해 Ajax(비동기적 자바스크립트와 XML)가 등장했고 페이지 전체가 아닌 일부를 업데이트하는 것이었습니다
- Ajax로 인해서 SPA가 대두되면서 이 기법을 이용한 개발이 관심사가 됐습니다
- Angular, Backbone, React, Vue 등의 프레임워크와 라이브러리가 등장하고 발전하게 됐습니다

## 비즈니스에 대한 고찰

> 💡 나만의 생각을 이야기해봅시다.
> 

### 프론트엔드 프레임워크가 등장하게 된 배경은 무엇일까?

- 모든 도구가 더 편하고 효과적인 도구로 끝없이 진화했듯이 개발 분야에도 더 편하게 효과적으로 기능을 구현할 수 있는 방법을 고민하고 만들게 됐다고 생각한다.

### 프론트엔드 개발자들은 현업에서 어떤 일을 하게 될까?

- 평소 공부하며 생각하는 프론트엔드 개발자 업무로는 웹 페이지의 화면을 구성하고 앞서 설계된 기능 정의에 따라서 서비스를 구현해내는 일을 한다.
- 프론트엔드 개발자라는 범위가 넓다고 생각한다. 당연하게도 기업마다 천차만별의 일을 할것이라 생각한다. 비교적 큰 기업인 경우에 세분화된 일을 할 것이고 규모가 작은 기업의 경우 웹 페이지 화면 및 기능부터 서버 통신 전반까지 역할을 맡는것이라 생각한다.

### 프론트엔드 개발자의 역할은 무엇일까?

- 궁극적인 목표는 최상의 서비스 제공이라 생각한다. 처음부터 설계된 서비스를 사용자가 사용할 수 있게 코드로 구현하여 제공하고 지속적으로 수정함을 통해서 더 편리한 서비스 제공에 힘쓰는 것이라 생각한다.

### 프론트엔드 씬에서 변하지 않는 기술은 무엇일까?

- 길지않은 학부과정을 거쳤음에도 대부분의 프로그래밍 언어는 변한다는 것을 느끼고 있다.
- 프론트엔드 개발자는 서비스 관점에 있어서 사용자와 더 가까운 관계에 있다고 생각한다. 사용자 관점에서 필요하고 편리한 서비스를 제공할 수 있는 공감 기술, 빠른 문제 발견 및 해결 기술이라 생각한다.

### 장기 생존을 위해 어떤 공부를 하면 좋을까?

- 시대가 급변하게 변하면서 개발은 편해지고 많은 지식이 필요없어져 가는것은 부정할 수없는 현실이고 미래이다. 이런 관점에서 기술적인 역량을 무조건적으로 높이려고 하기보다는 지속적으로 내가 기여할 수 있는 부분을 찾아서 끊임 없이 공부하는 것이 필요하다고 생각한다.
- 다양한 프레임워크, 라이브러리를 활용해도 방식은 엄청나게 변하지는 않음을 느낀다. 그 시대의 트렌드로 떠오르는 것들을 학습하고 활용하면서 문제 해결 능력을 지속적으로 늘리는게 좋지않을까 생각한다.

**Comment by JunilHwang** [comment]
지금은 "비즈니스에 대한 고찰" 부분이 무척 추상적으로 작성되어있습니다.
이를 조금 더 구체화시켜보면 어떨까요?

가령, "어떤 일"에 대해 조금 더 구체적으로 이야기해보자면
- 성능 최적화
- 웹접근성
- 크로스 브라우징
- 웹뷰
- 그래픽 작업 ( 캔버스, svg, webgl 등)
- 백오피스
- ..
이 외에도 수없이 많은 사례가 있겠네요.
현업에서 FE 개발자로 일하게 된다고 가정 하고서 더 깊게 고민해보면 좋을 것 같아요!
