### ISSUE TITLE
[Step1] 프레임워크에 대한 이해 (김호준)

### ISSUE THREAD

**Issue by hojunkim02** [DKU-D-Coding/js-study-make-framework-lv1#6]
### 브라우저, HTTP Protocol, HTML 등의 연관성에 대해 조사하기 (5문장 요약)

1. 브라우저는 인터넷을 통해 유저가 웹페이지에 접속하고 상호작용 할 수 있도록 해주는 응용 소프트웨어이다.
2. HTML 은 마크업 언어로서 웹페이지의 뼈대를 구성하는 데 사용되며, CSS, JS 와 함께 웹 프로그램의 기초 요소 중 하나이다.
3. 서버와의 상호작용을 위해 브라우저는 데이터를 주고받아야 하는데, 서버와 클라이언트의 종류에 따라 그 방법이 달라질 수 있다.
4. HTTP 프로토콜은 이러한 상황에서 어떻게 인터넷을 통해 데이터 전송 작업이 진행되어야 하는지를 정의한다.
5. 브라우저와 웹 서버는 Http 프로토콜을 통해 요청과 응답(request and response)을 주고받으며 동적인 웹페이지를 형성한다.

### DOM(Document Object Model) 조사하기 (3문장 요약)

1. 동적인 웹페이지를 구성하기 위해 개발자는 HTML 문서의 한 요소에 접근해야 할 필요가 있다.
2. DOM 은 HTML 또는 XML 문서를 위한 트리 구조의 인터페이스이다.
3. 개발자는 DOM 이 제공하는 구조를 통해 웹페이지의 한 요소에 접근하여 내용, 스타일 등을 바꿀 수 있다.

### BOM(Browser Object Model) 조사하기 (3문장 요약)

1. DOM 을 통해 개발자는 웹페이지를 변화시킬 수 있었지만, 이는 HTML 문서 외부의 이벤트에는 접근할 수 없었다.
2. BOM 은 브라우저가 제공하는 인터페이스로, 사용자의 브라우저 창, 뒤로가기, 클릭과 스크롤 등 사용자와 직접 관련된 이벤트들을 포함한다.
3. BOM 은 HTML 에 접근할 수 있는 DOM 과는 구별되며, DOM 과 함께 동적인 웹페이지를 구성하는 데에 사용된다.

### CSS(Cascading Style Sheet) 조사하기 (3문장 요약)

1. 솔직히 말해서, HTML 만 있는 웹사이트는 겁나 구리다.
2. CSS 는 HTML 에 스타일 요소를 추가할 수 있는 스타일 언어로, HTML 태그의 style attribute 를 통해 인라인 적용, <head> 태그 내부의 <style> 태그를 통해 적용하거나, 외부 파일을 가져와 적용 등의 방법이 있다.
3. 이름의 “Cascade” 에서 확인할 수 있듯, 마지막으로 적용된 요소가 적용된다.

### Javascript 조사하기 (3문장 요약)

1. HTML 에 CSS 까지 적용했다면 꽤 멋진 웹페이지가 되었겠지만, 나는 조금 더 동적인 페이지를 만들고 싶다.
2. JavaScript 는 브라우저 내부에서 사용할 수 있는 유일한 프로그래밍 언어로, 웹페이지의 정적 데이터에 접속하여 동적인 웹페이지를 만들 수 있도록 해준다.
3. AJAX 와 같은 기술은 사용자의 이벤트가 발생했을 때, 브라우저가 페이지 전체를 새로고침하지 않고 일부분만을 업데이트하도록 해준다.

### ECMAScript 조사하기 (3문장 요약)

1. 파이썬, 루비와 같은 언어를 사용하는 “일반적인” 프로그램과 달리, 브라우저는 브라우저를 통해 실행되는 모든 프로그램(웹페이지)의 정보를 브라우저 개발자가 가지고 있지 않다.
2. 또한 구글 크롬, 모질라 파이어폭스와 같이 브라우저를 만드는 회사는 그들 나름의 독자적인 브라우저 엔진을 가지고 있는데, 개발자는 브라우저에 따라 다른 웹페이지를 만들고 싶지 않다.
3. ECMAScript 는 이러한 웹 공통 호환성을 지키기 위해 존재하는 최소한의 표준으로, JavaScript 는 이러한 표준을 따르는 스크립트 언어이다.

### Javascript Framework가 등장한 배경에 대해 조사하기 (5문장 요약)

1. HTML, CSS, JavaScript 를 갖춘 웹페이지는 충분히 훌륭하고 멋있지만, 과연 우리는 이것만 가지고 “Netflix” 나 “YouTube” 와 같은 멋진 웹사이트를 만들 수 있을까? (좀 무리가 있어 보인다!)
2. 고대의 개발자들은 동적인 웹페이지를 쉽게 관리하기 위해 Java 나 C#, Ruby 같은 기존의 멋진 서버 기술들을 활용하여 서버에서 동적인 웹페이지를 직접 만들어 브라우저에 전송하는 방식을 활용하였다.
3. 하지만, 이러한 방식은 어떤 사용자 이벤트가 발생할 때 마다 페이지를 새로고침해야 하고, 또한 다시 웹페이지를 통째로 전송해야 했기에 비효율적으로 느껴졌다.
4. 고대의 개발자들은 이러한 문제를 해결하기 위해 바뀌어야 하는 일부 페이지만을 수정하는 기술들을 개발하기 시작했고, 또한 이외에 서버와 대화하기 위한 유용한 라이브러리들이 개발되었다.
5. 오랜 변화 끝에 React 와 같은 멋진 라이브러리가 업계에 등장했고, 또한 기존의 서버에서 사용하던 프레임워크의 형태가 프론트엔드에도 확립되기 시작했다.

### Vue와 React의 장단점에 대해 비교하기 (5가지)

> React 의 장점 (Vue 의 단점이기도 함)
> 
1. 거대한 커뮤니티와 Meta(전 Facebook)에 의해 강력히 지원받고 있다.
2. 오랫동안 업계에서 사용되어 환경이 잘 확립되어 있다.
3. 리액트의 가상 DOM 은 강력한 성능을 발휘하고 있다.
4. 강력한 개발자 도구들이 많이 마련되어 있다.
5. JavaScript, TypeScript, Dart 등 다양한 언어와 함께 지원되고 있다.

> Vue 의 장점 (React 의 단점이기도 함)
> 
1. 표현이 간단하여 배우고 사용하기가 쉽다.
2. 상태 관리, 라우팅 등의 기능을 기본적으로 제공한다.
3. 핵심 라이브러리가 더 작고 가볍다.
4. 동적 업데이트와 데이터 바인딩이 간편하다.

## 비즈니스에 대한 고찰

> 💡 나만의 생각을 이야기해봅시다.
> 

### 프론트엔드 프레임워크가 등장하게 된 배경은 무엇일까?

개발자에게 있어서 자주 사용되는 코드를 제거하고 큰 프로젝트를 구조적으로 정리하는 일이 특이한 일은 아니다. 하지만 백엔드에 비해 프론트엔드 프레임워크가 늦게 발전한 것은 다음 세 가지 이유라고 생각한다.

1. 옛날 JavaScript 가 구려서
2. 브라우저의 성능이 그리 좋지 못해서
3. 웹페이지에 배치해야 할 데이터들이 그정도로 동적이지 않아서

### 프론트엔드 개발자들은 현업에서 어떤 일을 하게 될까?

과거와 달리 현재의 프론트엔드는 서버와 매우 밀접하게 연결되어 있다. 리얼타임 게임부터 시작하여 실시간 회의 플랫폼, 방송 플랫폼 등은 이제 와서는 꽤 흔한 기술이 되었다. 그렇다면 현재 시점에서 프론트엔드 개발자가 실제로 하는 일은 뭘까 생각해보고 크게 세 가지 정도로 나누어보았다.

1. 그 흔한 코드 열심히 작성하기
2. 실사용 로그 수집과 최적화 작업
3. 핵심 기술 제공 방식에 대한 논의

### 프론트엔드 개발자의 역할은 무엇일까?

개발자를 필요로 하는 기업의 규모에 따라서 그 역할은 조금은 달라질 것이다.

1. 충분히 큰 규모라면, 프로그래밍적 기능의 구현에 집중해야 할 것이다.
2. 중간 정도의 규모라면, 기획자와 퍼블리셔들과의 협의도 또한 역할로서 더해질 것이다.
3. 작은 정도의 규모라면, 기획자, 퍼블리셔, 서버 개발의 영역도 어느 정도 걸치고 있을 수 있다.

### 프론트엔드 씬에서 변하지 않는 기술은 무엇일까?

정말 길게 보면 변하지 않는 기술은 없다고 생각한다. 하지만, 비교적 빠르게 변하는 프론트 씬에서 그래도 대체로 미덕으로 가지고 있을 수 있는 자세가 존재한다면, “타인의 의견 수용하기” 라고 생각한다.

이는 물론 어떤 분야에서도 필요한 덕목이지만, 특히 프론트 개발자에게 (또는 UX 와 관한 분야에서) 쉽게 간과될 수 있는 부분이다. 프론트 개발자는, “내 감각” 을 신뢰해서 생기는 오류가 발생할 가능성이 크다고 생각한다.

### 장기 생존을 위해 어떤 공부를 하면 좋을까?

어떤 기술 자체에만 매몰되지 말고, 나만의 분야를 만들어 지속적으로 관심을 가지고 공부할 수 있는 환경을 조성하는 것이 중요하다고 생각한다.

1. 나쁜 예 : 제이쿼리로 전문가가 되었지만 앵귤러나 리액트 시장을 무시하고 있다가 일자리를 잃은 개발자
2. 좋은 예 : 제이쿼리로 프론트 개발을 하고 있었으나 커뮤니티에 관심이 있어 채팅 앱 개발에도 관심을 가진 개발자

변화하는 업계에서 장기 생존은 분명 어려운 일이다. 어떤 상황에서든 끊임없는 대처 능력을 가지는 것이 무엇보다 중요할 것이다.

### 적당히 해본 프론트엔드에 대한 고찰

 나와 비슷한 나이대라면, 아마도 꽤나 흥미로운 학생 시절을 보냈을 것이다. 초등학교에 입학해서 처음 본 컴퓨터실에는 브라운관 모니터들이 있었고, 인터넷이 필요할 때는 “인터넷 익스플로러” 를 사용하는 것이 당연했다. 집에 오면 “닌텐도 DS” 를 가지고 놀면서, 가끔씩 비디오나 DVD로 영화를 보고, 테이프로 영어 공부를 했다. 또, 아이리버 mp3 와 시사 전자사전을 가지고 다니는 게 초등학생 나름의 간지였던 것 같다.

 막 고학년이 되었을 무렵, 대부분의 학생들은 꽤 멋진 “폴더폰” 이나 “터치폰” 이라고 부르는 핸드폰을 가지고 있었다. 그런데 조만간 부모님이 재밌는 물건을 가지고 왔다. “아이폰 4” 라는 핸드폰인데, 엄청 큰 화면에 “밀어서 잠금해제” 라는 기능이 재밌다.

 2010년, 한국은 이미 인터넷 보급률이 60% 를 넘어섰다. 이 무렵 학교에서는 “UCC 제작” 이 큰 인기를 끌고 있었고, 그 때는 몰랐지만 아마 세계적인 유행이었던 것 같다. 프론트엔드 씬에서 보자면, “제이쿼리”, “액션스크립트” 와 같은 기술들이 적극적으로 사용되던 시기이다. 또한 “유튜브” 라는 서비스가 인기를 얻고, 흔히 “인터넷 방송인” 이라는 사람들이 업계에 진출하기 시작했다.

 왜 프레임워크가 필요할까, 그런 질문 이전에 어떻게 프론트엔드가 발전했을까, 라는 질문에 답하고 싶었다. 아마도 나를 포함한 내 또래 친구들은 모두가 현재의 프론트엔드 생태계를 만들기 위해 타겟에 되었던 엔드 유저일 것이다. 또한 새로운 기술들 속에 빠르게 적응한 “밀레니얼 세대” 들은 현재 미디어 사회를 선도하고 있다.

 IT 기술, 특히 프론트엔드 기술은 유저 수의 증가, 미디어의 증가와 밀접한 관련이 있다. 친구와 친구 사이를 잇고 (connect peer to peer), 클릭 몇 번으로 더 넓은 세상과 접하게 된다. 그래서 프론트엔드를 발전시키다는 것은 무엇일까? 라는 질문에 대해 나는 “더 잘 연결하기 위해 노력하는 것” 이라고 생각하게 되었다.

### 참고 자료

[Web Tech](https://nekoforsale.vercel.app/web-tech)

**Comment by JunilHwang** [comment]
react의 1 ~ 4 번은 vue의 장점이기도 한답니다!

**Comment by JunilHwang** [comment]
> 정말 길게 보면 변하지 않는 기술은 없다고 생각한다. 하지만, 비교적 빠르게 변하는 프론트 씬에서 그래도 대체로 미덕으로 가지고 있을 수 있는 자세가 존재한다면, “타인의 의견 수용하기” 라고 생각한다.
이는 물론 어떤 분야에서도 필요한 덕목이지만, 특히 프론트 개발자에게 (또는 UX 와 관한 분야에서) 쉽게 간과될 수 있는 부분이다. 프론트 개발자는, “내 감각” 을 신뢰해서 생기는 오류가 발생할 가능성이 크다고 생각한다.

이건 "소프트스킬" 같아요 ㅋㅋ 
"하드스킬" 관점에서의 "변하지 않는" 영역도 있지 않을까요?

**Comment by hojunkim02** [comment]
> react의 1 ~ 4 번은 vue의 장점이기도 한답니다!

앗 그런가요?! 전반적으로 vue 가 커뮤니티가 좀 부족하다고 생각하고 있었는데 찾아봐야겠네요..

**Comment by hojunkim02** [comment]
> > 정말 길게 보면 변하지 않는 기술은 없다고 생각한다. 하지만, 비교적 빠르게 변하는 프론트 씬에서 그래도 대체로 미덕으로 가지고 있을 수 있는 자세가 존재한다면, “타인의 의견 수용하기” 라고 생각한다.
> > 이는 물론 어떤 분야에서도 필요한 덕목이지만, 특히 프론트 개발자에게 (또는 UX 와 관한 분야에서) 쉽게 간과될 수 있는 부분이다. 프론트 개발자는, “내 감각” 을 신뢰해서 생기는 오류가 발생할 가능성이 크다고 생각한다.
> 
> 이건 "소프트스킬" 같아요 ㅋㅋ "하드스킬" 관점에서의 "변하지 않는" 영역도 있지 않을까요?

아.. 하드스킬 관점에서 쓰고 싶었는데 "언어 지식" 외에는 그럴듯한 답안이 생각나질 않아서 ㅎㅎ...
웹 공부하다 보면 php, 제이쿼리 같이 정말 많이 쓰던 기술들도 어느 순간 파사삭 되는 순간이 오는구나 느껴지더라구요 ㅠ

**Comment by JunilHwang** [comment]
@hojunkim1
웹 자체는 어떨까요!?
가령 직접 브라우저를 만들어보면서 브라우저가 어떻게 생겼는지 깨우친다거나..? ㅋㅋㅋ
네트워크도 변하지 않는 기술에 포함되지 않을까요?
언어에 종속적이지 않고,
프레임워크에 종속적이지 않고,
라이브러리에 종속적이지 않은게 분명 있으리라 생각해요!
