### ISSUE TITLE
[Step1] 프레임워크에 대한 이해(김채은)

### ISSUE THREAD

**Issue by chchaeun** [DKU-D-Coding/js-study-make-framework-lv1#7]
###  브라우저, HTTP Protocol, HTML 등의 연관성에 대해 조사하기 (5문장 요약)
웹 페이지를 표시하기 위한 HTML이 서버에 저장되어 있다고 하면, 브라우저는 서버로부터 해당 데이터를 전송 받아 렌더링 엔진을 통해 텍스트와 이미지 등으로 구성된 화면으로 변환하여 표시한다. 또한 필요에 따라 서버에게 데이터를 전송할 수도 있다. 브라우저가 서버와 HTML을 비롯한 데이터를 주고받을 때는 HTTP라는 통신 규약을 따라야 한다.

###  DOM(Document Object Model) 조사하기 (3문장 요약)
DOM은 HTML 문서에 대한 인터페이스이다. 원본 HTML 문서를 객체 기반 트리로 표현한다. 뷰 포트에 무엇을 렌더링할지 결정하기 위해서, 자바스크립트를 사용해 페이지를 변경하기 위해 사용된다.

###  BOM(Browser Object Model) 조사하기 (3문장 요약)
BOM은 문서 이외의 브라우저의 정보나 기능을 제어하기 위해 브라우저가 제공하는 추가 객체이다. 대부분의 브라우저에서 구현돼있지만 정의나 표준이 없어서 브라우저마다 세부사항이 다르다. 대표적으로 window, navigator, location 등의 객체가 있다.

###  CSS(Cascading Style Sheet) 조사하기 (3문장 요약)
CSS는 HTML나 XML 문서의 디자인을 입힐 때 사용하는 스타일 시트 언어이다. Cascading은 ‘폭포’, ‘위에서 아래로 쏟아지는’이라는 뜻을 가지는데, 이처럼 CSS는 스타일의 우선 순위와 상속을 통해 어떤 요소에 스타일을 적용할지 결정한다.

###  Javascript 조사하기 (3문장 요약)
JavaScript는 웹 페이지를 동적으로 만들기 위해 고안된 프로그래밍 언어이다. 표준 HTML 문서 내에 삽입되어 사용되는 스크립트 언어이다. 프로토타입을 상속하는 프로토타입 기반 객체 지향 언어이다.

###  ECMAScript 조사하기 (3문장 요약)
ECMAScript는 ECMA-262 기술 규격에 의해 정의된 범용 스크립트 언어이다. 자바스크립트를 표준화하기 위해 만들어졌는데, 현재는 자바스크립트가 이 표준을 따르고 있다. ES6에서 이전 버전의 문제들이 많이 해결되고, 간결한 문법들이 추가되며 가독성과 유지보수성을 향상했다.

###  Javascript Framework가 등장한 배경에 대해 조사하기 (5문장 요약)
프레임워크는 특정 프로그램을 개발하기 위한 여러 요소들과 매뉴얼을 제공하는 프로그램이다. 초기 자바스크립트에서는 모듈이라는 개념이 없어 모든 변수가 전역 공간에 있었고, NPM이 없어 외부 라이브러리를 직접 다운로드하여 script 태그로 불러와야 하는 등 시스템이 갖춰져 있지 않았다. 구조화된 스크립트를 통해 반복적으로 해야 하는 공통부분을 최소화하고 개발 품질을 향상하기 위해 자바스크립트 프레임워크가 등장한 것이다.

###  Vue와 React의 장단점에 대해 비교하기 (5가지)
- React는 라이브러리이고, Vue는 프레임워크이다. React는 대부분 자바스크립트 문법을 사용하여 구현할 수 있지만 Vue는 고유의 문법을 사용하는 경우가 많다. 자바스크립트에 능숙한 사람이면 React를 빠르게 배울 수 있을 것이지만, 그렇지 않다면 방대한 양의 자바스크립트 문법을 익히는 것보다 Vue를 배우는 게 빠를 수 있다.
- React는 생태계가 넓어 모듈과 커뮤니티, 라이브러리를 보다 자유롭게 이용할 수 있다.
- Vue는 렌더링 중 컴포넌트의 종속성이 자동 추적되어 시스템이 실제로 다시 렌더링하는 컴포넌트를 정확히 알고 있다. React는 상태가 변경되면 해당 컴포넌트부터 자식 컴포넌트를 포함하는 트리를 다시 렌더링한다. 기본적으로 성능 면에서 좋지 않다.
- React의 생태계가 Vue보다 훨씬 크다. 모듈, 커뮤니티 등을 더욱 자유롭게 활용할 수 있다.

## 비즈니스에 대한 고찰

> 💡 나만의 생각을 이야기해봅시다.

###  프론트엔드 프레임워크가 등장하게 된 배경은 무엇일까?
웹의 발전에 따라 페이지 이동 시 새로고침 없이 네이티브 앱과 유사한 사용자 경험을 주는 SPA가 등장했다. SPA는 자바스크립트만으로 개발하기에 복잡하며 반복되는 작업이 많아 이를 프레임워크 또는 라이브러리화 하여 생산성을 높이기 위해 등장했다고 생각한다.

###  프론트엔드 개발자들은 현업에서 어떤 일을 하게 될까?
프론트엔드 개발자는 HTML과 CSS로 디자인된 화면을 구현하고, HTTP 통신을 통해 서버에서 데이터를 받아와 사용자가 보는 화면에 렌더링하는 일을 맡는다. 전자는 웹 퍼블리셔라는 직업으로 구분되기도 하지만, 많은 회사들에서 프론트엔드 개발자가 퍼블리싱까지 맡는 경우가 많기 때문에 HTML과 CSS도 프론트엔드 개발자가 가져야 할 필수적인 역량이다.

###  프론트엔드 개발자의 역할은 무엇일까?
- 화면에 필요한 데이터가 있을 때 API에 대한 추가/수정 요청을 해야 하기 때문에 API에 대한 이해가 필요하다.
- 화면을 개발할 뿐만 아니라 오류를 사전에 방지하고, 오류가 발생했을 때 빠르게 확인할 수 있도록 테스트 환경을 구축해야 한다.
- UX, 웹 표준, 웹 접근성을 고려하여 개발한다.

###  프론트엔드 씬에서 변하지 않는 기술은 무엇일까?
- 최근에 파이스크립트와 같은 기술이 나오고는 있지만 아직까지는 웹에서 떼어놓을 수 없는 기술이 자바스크립트이다. 프레임워크, 라이브러리는 빠르게 발전하고 있지만 모두 자바스크립트에 근간을 두고 있으므로 자바스크립트에 대한 이해는 필수적이다.
- HTML 마크업은 웹 접근성, 검색 엔진 기술과 밀접하게 연관되어 있기 때문에 쉽게 변하지 않을 것 같다.

###  장기 생존을 위해 어떤 공부를 하면 좋을까?
프론트엔드 개발자로서 기본을 갖추면서, 어필할 수 있는 특장점 필요하다. 기본적으로 갖춰야 할 것은 웹 표준과 웹 접근성을 준수한 마크업 작성, 자바스크립트에 대한 딥다이브한 지식 등이 있을 것이다. 어필할 수 있는 요소로는 렌더링 최적화, 웹 테스트 기술, 웹뷰 네이티브 포맷팅 등을 갖출 수 있다.

**Comment by JunilHwang** [comment]
와 ㅋㅋㅋ 군더더기 없이 작성하셨네요!! 좋습니다 👏👏
그리고 채은님은 웹표준과 접근성에 관심이 많은 것 같아요 👍

> 웹에서 떼어놓을 수 없는 기술이 자바스크립트

다른 관점에서 보자면, [웹 API](https://developer.mozilla.org/ko/docs/Web/API) 같은 것들이 언어와 상관없이 웹의 인터페이스를 다루기 때문에 더 중요하지 않을까 싶습니다.
자바스크립트도 웹 API의 구현체일 뿐이니까요!

> UX, 웹 표준, 웹 접근성을 고려하여 개발한다.

이를 토대로 어떤 상업적 가치를 창출할 수 있을까요?

**Comment by chchaeun** [comment]
UX에 대한 고려는 리텐션에 영향을 미칠 것 같아요. 같은 서비스를 주더라도 조금 더 편리하게 사용할 수 있는 앱이 더 선호되기 때문에 꾸준한 고객층을 확보하는 데에 도움이 될 것 같습니다!
웹 표준을 지켰을 때는 검색엔진최적화에 도움이 되기 때문에 사용자 유입에서 이점이 있을 것 같아요. 
웹 접근성은 법 준수 측면에서만 생각해봤는데... 상업적 가치 측면이라면 더 넓은 사용자층이 확보된다는 이점이 있지 않을까...? 싶습니다!
