### ISSUE TITLE
[Step1] 프레임워크에 대한 이해(이호연)

### ISSUE THREAD

**Issue by ho991217** [DKU-D-Coding/js-study-make-framework-lv1#8]
###  브라우저, HTTP Protocol, HTML 등의 연관성에 대해 조사하기 (5문장 요약)
HTTP Protocol은 서버와 클라이언트 사이에서 데이터를 주고 받는 방법을 정해 놓은 규칙이다. 브라우저는 해당 규칙을 따라 HTTP를 통해 서버로부터 데이터를 받아와 HTML로 해석하여 보여준다. 브라우저는 HTML 문서를 DOM(Document Object Model)으로 변환하여 브라우저의 내부 객체로 만든다. 그리고 객체들을 조작할 수 있는 BOM(Browser Object Model)이 생기고, CSS(Cascading Style Sheet)를 통해 디자인을 하고, Javascript를 통해 동적으로 웹 애플리케이션을 만들 수 있게 된다. 그리고 프론트엔드 개발을 위한 Javascript의 표준인 ECMAScript도 등장하게 되었다.

###  DOM(Document Object Model) 조사하기 (3문장 요약)
DOM(Document Object Model)은 HTML 문서를 객체로 바꾸어 브라우저의 내부 객체로 만드는 방법이다. DOM은 노드 모델로 구성되어 객체를 조작하고 해당 객체들의 속성과 메소드를 조작하기 위해 사용된다. 이를 통해 동적으로 HTML 문서를 조작할 수 있게 된다.

###  BOM(Browser Object Model) 조사하기 (3문장 요약)
BOM(Browser Object Model)은 브라우저의 내부 객체로 만들어진 DOM을 조작하기 위한 메소드들을 제공하는 객체이다. 이를 통해 브라우저의 창의 속성과 크기, 탭, 링크 등을 관리할 수 있고, 브라우저의 메뉴, 단축키, 히스토리, 쿠키 등을 관리할 수 있다.

###  CSS(Cascading Style Sheet) 조사하기 (3문장 요약)
CSS(Cascading Style Sheet)는 웹 문서의 디자인을 꾸미기 위한 스타일 시트 언어이다. 이는 HTML 문서에 스타일을 적용하기 위해 만들어졌고, 배경 색상, 글자 색상, 너비, 높이, 테두리 등 기본적인 스타일을 적용할 수 있다. 또한 전체 레이아웃을 구성하기 위해 레이아웃 메커니즘, 박스 모델, 플로팅, 포지셔닝 등 다양한 속성을 사용할 수 있다.

###  Javascript 조사하기 (3문장 요약)
Javascript는 브라우저 및 서버측 프로그래밍 언어이다. 브라우저에서는 DOM과 BOM을 조작하고, 데이터를 주고 받고, 사용자 인터페이스를 만들고, 반응형 웹페이지를 구성하기 위해 사용된다. 서버측 프로그래밍에서는 데이터베이스 연결, 서버 동작, 메일 전송, 이미지 업로드 등과 같은 업무를 담당한다. ECMAScript와 다양한 라이브러리를 통해 다양한 기능을 구현할 수 있다.

###  ECMAScript 조사하기 (3문장 요약)
ECMAScript는 Javascript의 표준 버전이다. ECMAScript의 목적은 프론트엔드 개발을 위한 Javascript의 스펙을 정하고, 브라우저 간의 코드의 호환성을 높이기 위한 것이며, 프론트엔드 개발에 필요한 기능들 중 기본적인 기능들을 제공한다. ECMAScript에는 변수, 객체, 함수, 제어문 등의 기본적인 개념과 메소드, 이벤트, 에러 핸들링, 네트워크 등의 고급 기능이 포함되어 있다.

###  Javascript Framework가 등장한 배경에 대해 조사하기 (5문장 요약)
Javascript Framework는 반응형 웹과 모바일 애플리케이션 개발을 위해 등장하게 되었다. 이로 인해 웹과 모바일 애플리케이션을 빠르고 쉽게 개발할 수 있게 되었고, 웹 개발의 생산성과 우수성을 높일 수 있게 되었다. 또한 다양한 플랫폼과 디바이스 사이의 동작의 일관성과 속도도 높일 수 있게 되었다. 그리고 자바스크립트를 통해 고급 애플리케이션을 개발할 수 있게 되었다. 따라서 다양한 Javascript Framework들이 등장하게 되었다.

###  Vue와 React의 장단점에 대해 비교하기 (5가지)
1. Vue는 단순하고 사용하기 쉽지만, React는 복잡하고 배우기 어렵다.
2. Vue는 기능이 간단하고 적은 코드로 작동하지만, React는 다양한 기능과 다양한 컴포넌트를 제공한다.
3. Vue는 HTML을 기반으로 만들어진 템플릿 시스템을 제공하고, React는 JSX를 통해 템플릿 시스템을 제공한다.
4. Vue는 단방향 데이터 흐름을 가지고 있지만, React는 반응성을 유지하기 위해 복잡한 데이터 흐름을 가지고 있다.
5. Vue는 웹 개발에 집중하고 있고, React는 모바일 애플리케이션 개발에도 사용할 수 있다.

## 비즈니스에 대한 고찰

> 💡 나만의 생각을 이야기해봅시다.

###  프론트엔드 프레임워크가 등장하게 된 배경은 무엇일까?
프론트엔드 프레임워크가 등장하게 된 배경은 빠르고 쉽게 웹과 모바일 애플리케이션을 개발하기 위해서이다. 또한, 개발에 소요되는 시간과 비용을 절약하기 위해, 다양한 플랫폼과 디바이스 사이의 동작의 일관성과 속도도 높일 수 있고, 고급 애플리케이션을 개발할 수 있게 되었기 때문이다.

###  프론트엔드 개발자들은 현업에서 어떤 일을 하게 될까?
프론트엔드 개발자들은 HTML, CSS, JavaScript 등의 기술을 사용하여 웹 및 모바일 애플리케이션을 개발하는 데 도움을 줄 것입니다. 개발자는 웹 페이지 및 애플리케이션의 기능을 설계하고 구현할 수 있습니다. 또한, 디자인과 사용자 경험에 관한 요구 사항을 분석하고 디자인 설계를 수행하는 데 도움을 줄 것입니다. 개발자는 또한 다양한 웹 표준을 준수하고 디버깅하고, 애플리케이션과 프레임워크를 업데이트하는 데 도움을 줄 것입니다.

###  프론트엔드 개발자의 역할은 무엇일까?
프론트엔드 개발자는 주어진 요구사항을 정확히 파악하고, 데이터의 흐름과 그에따른 결과를 속도 / 비용의 측면에서 효율적으로 나타내는 코드를 작성해야합니다.

###  프론트엔드 씬에서 변하지 않는 기술은 무엇일까?
절대로 변하지 않는 기술은 없다고 생각합니다. AI를 이용한 웹 디자인 및 퍼블리싱도 등장하고 있으며, 백엔드 명세를 가지고 프론트엔드 코드를 작성 해 주는 기술도 현재 개발 중에 있는 것으로 알고 있습니다. 따라서 변화하는 프론트엔드 씬에 맞춰 가지고 있는 지식과 기술등을 이용해 고차원의 가치를 창출 할 방식을 끊임없이 모색해야합니다.

###  장기 생존을 위해 어떤 공부를 하면 좋을까?
장기 생존을 위해 가장 중요한 것은 새로운 기술과 동향을 지속적으로 업데이트하는 것입니다. 또한, 디자인과 사용자 경험이 중요하므로 디자인 설계를 수행하기 위해 디자인 동향과 웹 표준을 이해하고 준수하는 것이 중요합니다.

**Comment by JunilHwang** [comment]
> Vue는 HTML을 기반으로 만들어진 템플릿 시스템을 제공하고, React는 JSX를 통해 템플릿 시스템을 제공한다.
Vue에서도 jsx를 사용할 수 있긴 합니다 ㅋㅋ

> 다양한 플랫폼과 디바이스 사이의 동작의 일관성과 속도도 높일 수 있고, 고급 애플리케이션을 개발할 수 있게 되었기 때문이다.
고급 어플리케이션을 개발할 때는 반대로 웹은 독이 되는게 아닐까요?
네이티브에 비해 느리고, 할 수 있는 일이 제한적이거든요!

> 절대로 변하지 않는 기술은 없다고 생각합니다.
- 네트워크나 OS 등은 어떨까요?
- 브라우저 자체는 어떨까요?
- Web API 는 어떨까요?

즉, 한 번 공부해놓으면 평생 가는 것들이 분명 있어요!
이에 대해서 깊게 고민해보면 좋을 것 같습니다 ㅎㅎ

> 장기 생존을 위해 어떤 공부를 하면 좋을까?
- JS 같은 언어를 "직접"만들 수 있는 기술을 가지고 있으면 어떨까요?
- 오픈소스를 공부해보는건 어떨까요?
